/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI.JPanel;

import com.team3.DAO.DAO_KhachHang;
import com.team3.DAO.DAO_PhieuDangKy;
import com.team3.Helpers.DateHelper;
import com.team3.Helpers.DialogHelper;
import com.team3.Helpers.ShareHelper;
import com.team3.Model.Model_KhachHang;
import com.team3.Model.Model_PhieuDangKy;
import java.awt.Image;
import java.awt.event.MouseEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell Vostro
 */
public class KhachHang extends javax.swing.JPanel {

    DAO_KhachHang dao = new DAO_KhachHang();
    DAO_PhieuDangKy daopdk = new DAO_PhieuDangKy();

    int index = 0;

    /**
     * Creates new form SoDoPhong
     */
    public KhachHang() {
        initComponents();
        load();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gioitinh = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pnlDSLP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pnlChiTiet = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        chitiet = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtHoTenKH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSDT_KH = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail_KH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        rdoNam_KH = new javax.swing.JRadioButton();
        rdoNu_KH = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtQuocTich = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblAnhCMND = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDiaChiKH = new javax.swing.JTextArea();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1250, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(938, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.X_AXIS));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(15, 610));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        pnlDSLP.setBackground(new java.awt.Color(255, 255, 255));
        pnlDSLP.setPreferredSize(new java.awt.Dimension(730, 570));
        pnlDSLP.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Họ Tên", "CMND", "SDT", "Email", "Giới tính", "Quốc tịch", "Địa chỉ", "Ngày thêm", "Hình ảnh"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhachHang.setRowHeight(22);
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);
        if (tblKhachHang.getColumnModel().getColumnCount() > 0) {
            tblKhachHang.getColumnModel().getColumn(0).setResizable(false);
            tblKhachHang.getColumnModel().getColumn(1).setResizable(false);
            tblKhachHang.getColumnModel().getColumn(2).setMinWidth(0);
            tblKhachHang.getColumnModel().getColumn(2).setPreferredWidth(0);
            tblKhachHang.getColumnModel().getColumn(2).setMaxWidth(0);
            tblKhachHang.getColumnModel().getColumn(3).setResizable(false);
            tblKhachHang.getColumnModel().getColumn(4).setMinWidth(0);
            tblKhachHang.getColumnModel().getColumn(4).setPreferredWidth(0);
            tblKhachHang.getColumnModel().getColumn(4).setMaxWidth(0);
            tblKhachHang.getColumnModel().getColumn(5).setResizable(false);
            tblKhachHang.getColumnModel().getColumn(6).setResizable(false);
            tblKhachHang.getColumnModel().getColumn(7).setResizable(false);
            tblKhachHang.getColumnModel().getColumn(8).setResizable(false);
            tblKhachHang.getColumnModel().getColumn(9).setMinWidth(0);
            tblKhachHang.getColumnModel().getColumn(9).setPreferredWidth(0);
            tblKhachHang.getColumnModel().getColumn(9).setMaxWidth(0);
        }

        pnlDSLP.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("      Danh sách khách hàng");
        jLabel2.setPreferredSize(new java.awt.Dimension(132, 25));
        pnlDSLP.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel2.add(pnlDSLP);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(20, 610));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);

        pnlChiTiet.setBackground(new java.awt.Color(255, 255, 255));
        pnlChiTiet.setPreferredSize(new java.awt.Dimension(500, 570));
        pnlChiTiet.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("      Chi tiết");
        jLabel3.setPreferredSize(new java.awt.Dimension(42, 25));
        pnlChiTiet.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        chitiet.setBackground(new java.awt.Color(255, 255, 255));
        chitiet.setLayout(new java.awt.GridLayout(3, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(6, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Họ tên");
        jPanel3.add(jLabel4);

        txtHoTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(txtHoTenKH);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("CMND");
        jPanel3.add(jLabel5);

        txtCMND.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(txtCMND);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("SDT");
        jPanel3.add(jLabel6);

        txtSDT_KH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.add(txtSDT_KH);

        chitiet.add(jPanel3);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new java.awt.GridLayout(6, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Email");
        jPanel8.add(jLabel7);

        txtEmail_KH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.add(txtEmail_KH);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Giới tính");
        jPanel8.add(jLabel8);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        rdoNam_KH.setBackground(new java.awt.Color(255, 255, 255));
        Gioitinh.add(rdoNam_KH);
        rdoNam_KH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNam_KH.setSelected(true);
        rdoNam_KH.setText("Nam");

        rdoNu_KH.setBackground(new java.awt.Color(255, 255, 255));
        Gioitinh.add(rdoNu_KH);
        rdoNu_KH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoNu_KH.setText("Nữ");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdoNam_KH)
                .addGap(18, 18, 18)
                .addComponent(rdoNu_KH)
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoNam_KH)
                    .addComponent(rdoNu_KH)))
        );

        jPanel8.add(jPanel7);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Quốc tịch");
        jPanel8.add(jLabel9);

        txtQuocTich.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.add(txtQuocTich);

        chitiet.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Địa chỉ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Ảnh CMND");

        lblAnhCMND.setBackground(new java.awt.Color(255, 255, 255));
        lblAnhCMND.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblAnhCMND.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAnhCMND.setPreferredSize(new java.awt.Dimension(0, 150));
        lblAnhCMND.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAnhCMNDMouseClicked(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        txtDiaChiKH.setColumns(20);
        txtDiaChiKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiaChiKH.setRows(5);
        jScrollPane2.setViewportView(txtDiaChiKH);

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnExport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnExport.setText("Xuất Excel DS Khách Hàng");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnhCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnSua)
                            .addComponent(btnLamMoi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExport))
                    .addComponent(lblAnhCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        chitiet.add(jPanel9);

        pnlChiTiet.add(chitiet, java.awt.BorderLayout.CENTER);

        jPanel2.add(pnlChiTiet);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(15, 610));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (check()) {
            this.update();
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        if (checkRole()) {
            delete();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void lblAnhCMNDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnhCMNDMouseClicked
        // TODO add your handling code here:
        UploadImage();
    }//GEN-LAST:event_lblAnhCMNDMouseClicked

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        // TODO add your handling code here:
        if (evt.getButton() == MouseEvent.BUTTON1) {
            index = tblKhachHang.rowAtPoint(evt.getPoint());
            edit();
        }

    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        if (DialogHelper.confirm(this, "Hãy chắc chắn bạn muốn trích xuất dữ liệu!")) {
            this.exportExcel(tblKhachHang);
        }
    }//GEN-LAST:event_btnExportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Gioitinh;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JPanel chitiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnhCMND;
    private javax.swing.JPanel pnlChiTiet;
    private javax.swing.JPanel pnlDSLP;
    private javax.swing.JRadioButton rdoNam_KH;
    private javax.swing.JRadioButton rdoNu_KH;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextArea txtDiaChiKH;
    private javax.swing.JTextField txtEmail_KH;
    private javax.swing.JTextField txtHoTenKH;
    private javax.swing.JTextField txtQuocTich;
    private javax.swing.JTextField txtSDT_KH;
    // End of variables declaration//GEN-END:variables

    void load() {
        DefaultTableModel model = (DefaultTableModel) tblKhachHang.getModel();
        model.setRowCount(0);
        try {
            List<Model_KhachHang> list = dao.select();
            for (Model_KhachHang kh : list) {
                Object[] row = new Object[]{
                    kh.getMaKH(),
                    kh.getHoTen(),
                    kh.getCmnd(),
                    kh.getSdt(),
                    kh.getEmail(),
                    kh.isGioiTinh() ? "Nam" : "Nữ",
                    kh.getQuocTich(),
                    kh.getDiaChi(),
                    DateHelper.toString(kh.getNgayThem(), "dd/MM/yyyy"),
                    kh.getHinh()
                };
                model.addRow(row);
            }
            if (list.size() > 0) {
                tblKhachHang.setRowSelectionInterval(index, index);
            }          
            txtHoTenKH.requestFocus();
            setButton(true);
        } catch (Exception e) {
            
        }
    }

    void clear() {
        txtHoTenKH.setText("");
        txtQuocTich.setText("");
        txtEmail_KH.setText("");
        txtSDT_KH.setText("");
        txtDiaChiKH.setText("");
        txtCMND.setText("");
        lblAnhCMND.setIcon(null);
        rdoNam_KH.setSelected(true);
        rdoNu_KH.setSelected(false);
        index = 0;
        load();
        setButton(true);
        txtCMND.setEnabled(true);
    }

    void insert() {
        try {
            Model_KhachHang model = getModel();
            dao.insert(model);
            clear();
            load();
            DialogHelper.alert(this, "Thêm thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Thêm không thành công");
        }
    }

    void update() {
        try {
            Model_KhachHang model = getModel();
            dao.update(model);
            clear();
            load();
            DialogHelper.alert(this, "Cập nhật thành công");
        } catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật không thành công");
        }
    }

    void delete() {
        int id = (int) tblKhachHang.getValueAt(this.index, 0);
        Model_PhieuDangKy model = daopdk.findById(String.valueOf(id));
        if (model == null) {
            try {
                dao.delete(String.valueOf(id));
                clear();
                load();
                DialogHelper.alert(this, "Xoá thành công");
            } catch (Exception e) {
                DialogHelper.alert(this, "Xoá không thành công");
            }
        } else {
            DialogHelper.alert(this, "Không thể xoá khách hàng");
        }
    }

    Model_KhachHang getModel() {
        Model_KhachHang model = new Model_KhachHang();
        model.setMaKH((int) tblKhachHang.getValueAt(this.index, 0));
        model.setHoTen(txtHoTenKH.getText());
        model.setQuocTich(txtQuocTich.getText());
        model.setEmail(txtEmail_KH.getText());
        model.setDiaChi(txtDiaChiKH.getText());
        model.setSdt(txtSDT_KH.getText());
        model.setCmnd(txtCMND.getText());
        model.setHinh(lblAnhCMND.getToolTipText());
        model.setNgayThem(DateHelper.now());
        if (rdoNam_KH.isSelected()) {
            model.setGioiTinh(true);
        } else {
            model.setGioiTinh(false);
        }
        return model;
    }

    void setModel(Model_KhachHang model) {
        txtHoTenKH.setText(model.getHoTen());
        txtQuocTich.setText(model.getQuocTich());
        txtEmail_KH.setText(model.getEmail());
        txtDiaChiKH.setText(model.getDiaChi());
        txtSDT_KH.setText(model.getSdt());
        txtCMND.setText(model.getCmnd());
        if (model.isGioiTinh() == true) {
            rdoNam_KH.setSelected(true);
            rdoNu_KH.setSelected(false);
        } else {
            rdoNam_KH.setSelected(false);
            rdoNu_KH.setSelected(true);
        }
        if (model.getHinh() != null) {
            Image im = ShareHelper.readLogo(model.getHinh()).getImage();
            ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnhCMND.getWidth(), lblAnhCMND.getHeight(), im.SCALE_SMOOTH));
            lblAnhCMND.setIcon(icon);
        } else {
            lblAnhCMND.setIcon(null);
        }
    }

    void edit() {
        try {
            int id = (Integer) tblKhachHang.getValueAt(this.index, 0);
            String oldimg = (String) tblKhachHang.getValueAt(this.index, 9);
            Model_KhachHang model = dao.findById(id);
            if (model != null) {
                setModel(model);
                setButton(false);
                txtCMND.setEnabled(false);
                lblAnhCMND.setToolTipText(oldimg);
            }
        } catch (Exception e) {
            
        }
    }

    void setButton(boolean value) {
        btnSua.setEnabled(!value);
        btnXoa.setEnabled(!value);
    }

    void UploadImage() {
        JFileChooser jfile = new JFileChooser();
        jfile.setDialogTitle("Chọn hình chứng minh nhân dân");
        if (jfile.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = jfile.getSelectedFile();
            if (ShareHelper.savelogo(file)) {
                Image im = ShareHelper.readLogo(file.getName()).getImage();
                ImageIcon icon = new ImageIcon(im.getScaledInstance(lblAnhCMND.getWidth(), lblAnhCMND.getHeight(), im.SCALE_SMOOTH));
                lblAnhCMND.setIcon(icon);
                lblAnhCMND.setToolTipText(file.getName());
            }
        }
    }

    boolean check() {
        if (checkLength() && checkHoten() && checkCMND() && checkSDT() && checkEmail() && checkQuoctich()) {
            return true;
        } else {
            return false;
        }
    }

    boolean checkLength() {
        if (txtHoTenKH.getText().length() > 0 && txtCMND.getText().length() > 0 && txtSDT_KH.getText().length() > 0 && txtEmail_KH.getText().length() > 0
                && txtQuocTich.getText().length() > 0 && txtDiaChiKH.getText().length() > 0) {
            return true;
        } else {
            DialogHelper.alert(this, "Tất cả thông tin không được để trống");
            return false;
        }
    }

    boolean checkSDT() {
        String sdt = "[0-9]{9,10}";
        if (txtSDT_KH.getText().trim().matches(sdt)) {
            return true;
        } else {
            DialogHelper.alert(this, "Điện thoại chỉ nhập số và có từ 9 - 10 số");
            txtSDT_KH.requestFocus();
            return false;
        }

    }

    boolean checkCMND() {
        String cmnd = "[0-9]{9,12}";
        if (txtCMND.getText().trim().matches(cmnd)) {
            return true;
        } else {
            DialogHelper.alert(this, "Chứng minh chỉ nhập số và có từ 9 - 12 số");
            txtCMND.requestFocus();
            return false;
        }
    }

    boolean checkHoten() {
        if (!txtHoTenKH.getText().trim().matches("^[a-zA-Z_ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶ"
                + "ẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợ"
                + "ụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\s]+$") || txtHoTenKH.getText().trim().equals("")) {
            DialogHelper.alert(this, "Họ tên không được nhập số");
            txtHoTenKH.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    boolean checkQuoctich() {
        if (!txtQuocTich.getText().trim().matches("^[a-zA-Z_ÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶ"
                + "ẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợ"
                + "ụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\s]+$") || txtQuocTich.getText().trim().equals("")) {
            DialogHelper.alert(this, "Quốc tịch không được nhập số");
            txtQuocTich.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    boolean checkEmail() {
        String email = "\\w+@\\w+\\.\\w+";
        String email2 = "\\w+@\\w+\\.\\w+\\.\\w+";
        if (txtEmail_KH.getText().trim().matches(email) || txtEmail_KH.getText().trim().matches(email2)) {
            return true;
        } else {
            DialogHelper.alert(this, "Email phải đúng định dạng");
            txtEmail_KH.requestFocus();
            return false;
        }
    }

    boolean checkCMNDexist() {
        List<Model_KhachHang> list = dao.select();
        for (Model_KhachHang kh : list) {
            if (txtCMND.getText().trim().equalsIgnoreCase(kh.getCmnd().trim())) {
                DialogHelper.alert(this, "Số chứng minh thư đã tồn tại");
                txtCMND.requestFocus();
                return false;
            }
        }
        return true;
    }

    boolean checkRole() {
        if (ShareHelper.role == 2) {
            return true;
        } else {
            DialogHelper.alert(this, "Chỉ có quản lý mới được quyền thao tác");
            return false;
        }
    }
    public void exportExcel(JTable table) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new FileNameExtensionFilter("Microsoft 97/2003 Worksheet Book - *.xls ","xls"));
        int i = chooser.showSaveDialog(chooser);
        if (i == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
                FileWriter out = new FileWriter(file+".xls");
                BufferedWriter bwrite = new BufferedWriter(out);
                DefaultTableModel model = (DefaultTableModel) table.getModel();
                // ten Cot
                for (int j = 0; j < table.getColumnCount(); j++) {
                    bwrite.write(model.getColumnName(j) + "\t");
                }
                bwrite.write("\n");
                // Lay du lieu dong
                for (int j = 0; j < table.getRowCount(); j++) {
                    for (int k = 0; k < table.getColumnCount(); k++) {
                        bwrite.write(model.getValueAt(j, k) + "\t");
                    }
                    bwrite.write("\n");
                }
                bwrite.close();
                DialogHelper.alert(this, "Trích xuất thành công!");
            } catch (Exception e) {
                DialogHelper.alert(this, "Lỗi trích xuất bảng!");
            }
        }
    }
}
