/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI.JPanel;

import com.team3.DAO.DAO_Phong;
import com.team3.Model.Model_Phong;
import java.util.List;
import com.Library.WrapLayout;
import com.team3.DAO.DAO_KhachHang;
import com.team3.DAO.DAO_LoaiPhong;
import com.team3.DAO.DAO_PhieuDangKy;
import com.team3.Helpers.DateHelper;
import com.team3.Helpers.DialogHelper;
import com.team3.Model.Model_KhachHang;
import com.team3.Model.Model_LoaiPhong;
import com.team3.Model.Model_PhieuDangKy;
import com.team3.UI.MenuChucNang;
import com.team3.UI.ThemPhong;
import java.awt.Dialog;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Dell Vostro
 */
public class SoDoPhong extends javax.swing.JPanel {
    DAO_Phong dao = new DAO_Phong();
    DAO_LoaiPhong lpdao = new DAO_LoaiPhong();
    DAO_PhieuDangKy dkdao = new DAO_PhieuDangKy();
    DAO_KhachHang khdao = new DAO_KhachHang();
    /**
     * Creates new form SoDoPhong
     */
    public SoDoPhong() {
        initComponents();
        WrapLayout wrapper = new WrapLayout();
        wrapper.setHgap(15);
        wrapper.setVgap(10);
        BlockItems.setLayout(wrapper);
        dcNgay.setEnabled(false);
        dcNgay.setEnabled(false);
        this.loadBlock();
        this.loadTang();
        this.loadLoaiPhong();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGR = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel30 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        btnQuaHan = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        chkFilterTang = new javax.swing.JCheckBox();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        cboLoaiPhong = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        cboTang = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        chkNgay = new javax.swing.JCheckBox();
        chkCMND = new javax.swing.JCheckBox();
        jPanel23 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        dcNgay = new com.toedter.calendar.JDateChooser();
        jPanel22 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        txtTenPhong = new javax.swing.JTextField();
        jPanel25 = new javax.swing.JPanel();
        chkTimPhong = new javax.swing.JCheckBox();
        chkFinder = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        BlockItems = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1250, 670));
        setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1250, 60));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("  SƠ ĐỒ PHÒNG");
        jPanel2.add(jLabel1, java.awt.BorderLayout.WEST);

        jPanel30.setBackground(new java.awt.Color(153, 51, 0));
        jPanel30.setPreferredSize(new java.awt.Dimension(700, 60));
        jPanel30.setLayout(new java.awt.GridLayout(1, 4));

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_plus_math_15px.png"))); // NOI18N
        jButton9.setText("Thêm Phòng");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel30.add(jButton9);

        btnQuaHan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnQuaHan.setText("Chức năng khác");
        btnQuaHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuaHanActionPerformed(evt);
            }
        });
        jPanel30.add(btnQuaHan);

        btnShowAll.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnShowAll.setText("Hiển thị tất cả phòng");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });
        jPanel30.add(btnShowAll);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/timkiem.png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel30.add(jButton8);

        jPanel2.add(jPanel30, java.awt.BorderLayout.EAST);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(1250, 150));
        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new java.awt.GridLayout(2, 2));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("  Loại phòng:");
        jPanel11.add(jLabel6);

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setLayout(new java.awt.GridLayout(1, 2));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tầng:");
        jPanel19.add(jLabel5);

        chkFilterTang.setBackground(new java.awt.Color(255, 255, 255));
        chkFilterTang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkFilterTang.setText("Lọc theo tầng");
        chkFilterTang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFilterTangItemStateChanged(evt);
            }
        });
        chkFilterTang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chkFilterTangMouseClicked(evt);
            }
        });
        jPanel19.add(chkFilterTang);

        jPanel11.add(jPanel19);

        jPanel13.setBackground(java.awt.Color.white);
        jPanel13.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(10, 37));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel14, java.awt.BorderLayout.WEST);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setPreferredSize(new java.awt.Dimension(10, 37));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel13.add(jPanel15, java.awt.BorderLayout.EAST);

        cboLoaiPhong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cboLoaiPhongMouseReleased(evt);
            }
        });
        jPanel13.add(cboLoaiPhong, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel13);

        jPanel16.setBackground(java.awt.Color.white);
        jPanel16.setLayout(new java.awt.BorderLayout());

        jPanel17.setBackground(java.awt.Color.white);
        jPanel17.setPreferredSize(new java.awt.Dimension(10, 37));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel17, java.awt.BorderLayout.WEST);

        jPanel18.setBackground(java.awt.Color.white);
        jPanel18.setPreferredSize(new java.awt.Dimension(10, 37));

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel16.add(jPanel18, java.awt.BorderLayout.EAST);

        cboTang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboTang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel16.add(cboTang, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel16);

        jPanel9.add(jPanel11);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new java.awt.GridLayout(2, 3));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Tìm theo ngày trả:");
        jPanel12.add(jLabel7);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Tìm theo phòng:");
        jPanel12.add(jLabel2);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkNgay.setBackground(new java.awt.Color(255, 255, 255));
        chkNgay.setText("Bật tìm theo ngày trả");
        chkNgay.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkNgayItemStateChanged(evt);
            }
        });
        jPanel21.add(chkNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 19, -1, -1));

        chkCMND.setBackground(new java.awt.Color(255, 255, 255));
        chkCMND.setText("Tìm theo CMND đặt phòng");
        chkCMND.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkCMNDItemStateChanged(evt);
            }
        });
        jPanel21.add(chkCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, -1, 30));

        jPanel12.add(jPanel21);

        jPanel23.setLayout(new java.awt.BorderLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setPreferredSize(new java.awt.Dimension(10, 37));
        jPanel20.setLayout(new java.awt.GridLayout(1, 0));
        jPanel20.add(dcNgay);

        jPanel23.add(jPanel20, java.awt.BorderLayout.CENTER);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setPreferredSize(new java.awt.Dimension(10, 37));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel22, java.awt.BorderLayout.EAST);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setPreferredSize(new java.awt.Dimension(10, 37));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel23.add(jPanel26, java.awt.BorderLayout.WEST);

        jPanel12.add(jPanel23);

        jPanel24.setLayout(new java.awt.BorderLayout());

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));
        jPanel27.setPreferredSize(new java.awt.Dimension(10, 37));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel24.add(jPanel27, java.awt.BorderLayout.WEST);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setPreferredSize(new java.awt.Dimension(10, 37));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 37, Short.MAX_VALUE)
        );

        jPanel24.add(jPanel28, java.awt.BorderLayout.EAST);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setPreferredSize(new java.awt.Dimension(10, 37));
        jPanel29.setLayout(new java.awt.GridLayout(1, 0));

        txtTenPhong.setEnabled(false);
        jPanel29.add(txtTenPhong);

        jPanel24.add(jPanel29, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel24);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chkTimPhong.setBackground(new java.awt.Color(255, 255, 255));
        chkTimPhong.setText("Bật tìm theo phòng");
        chkTimPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkTimPhongItemStateChanged(evt);
            }
        });
        jPanel25.add(chkTimPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, -1));

        chkFinder.setBackground(new java.awt.Color(255, 255, 255));
        chkFinder.setText("Tìm phòng trống");
        chkFinder.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkFinderItemStateChanged(evt);
            }
        });
        jPanel25.add(chkFinder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 23, -1, 14));

        jPanel12.add(jPanel25);

        jPanel9.add(jPanel12);

        jPanel4.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jPanel31.setBackground(new java.awt.Color(255, 255, 255));
        jPanel31.setPreferredSize(new java.awt.Dimension(15, 75));

        javax.swing.GroupLayout jPanel31Layout = new javax.swing.GroupLayout(jPanel31);
        jPanel31.setLayout(jPanel31Layout);
        jPanel31Layout.setHorizontalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel31Layout.setVerticalGroup(
            jPanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel31, java.awt.BorderLayout.EAST);

        jPanel32.setBackground(new java.awt.Color(255, 255, 255));
        jPanel32.setPreferredSize(new java.awt.Dimension(15, 75));

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        jPanel10.add(jPanel32, java.awt.BorderLayout.WEST);

        jPanel33.setLayout(new java.awt.GridLayout(2, 1));

        jPanel34.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Trạng thái phòng:");
        jPanel34.add(jLabel3, java.awt.BorderLayout.CENTER);

        jPanel33.add(jPanel34);

        jPanel35.setLayout(new java.awt.GridLayout(1, 7, 5, 0));

        jButton11.setBackground(new java.awt.Color(48, 55, 79));
        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/VIP.png"))); // NOI18N
        jButton11.setText("Phòng VIP");
        jButton11.setContentAreaFilled(false);
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.setIconTextGap(10);
        jButton11.setOpaque(true);
        jPanel35.add(jButton11);

        jButton3.setBackground(java.awt.Color.darkGray);
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_ok_20px_3.png"))); // NOI18N
        jButton3.setText("Phòng Trống");
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setIconTextGap(10);
        jButton3.setOpaque(true);
        jPanel35.add(jButton3);

        jButton5.setBackground(new java.awt.Color(53, 161, 71));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_money_box_20px.png"))); // NOI18N
        jButton5.setText("Đặt Trước");
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setIconTextGap(10);
        jButton5.setOpaque(true);
        jPanel35.add(jButton5);

        jButton6.setBackground(new java.awt.Color(163, 73, 214));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_sleeping_in_bed_20px.png"))); // NOI18N
        jButton6.setText("Đang Ở");
        jButton6.setContentAreaFilled(false);
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.setIconTextGap(10);
        jButton6.setOpaque(true);
        jPanel35.add(jButton6);

        jButton7.setBackground(new java.awt.Color(23, 162, 184));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_traveler_20px.png"))); // NOI18N
        jButton7.setText("Sắp/Hết Hạn");
        jButton7.setContentAreaFilled(false);
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setIconTextGap(10);
        jButton7.setOpaque(true);
        jPanel35.add(jButton7);

        jButton4.setBackground(new java.awt.Color(180, 156, 87));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_broom_20px.png"))); // NOI18N
        jButton4.setText("Phòng Bẩn");
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setIconTextGap(10);
        jButton4.setOpaque(true);
        jPanel35.add(jButton4);

        jButton2.setBackground(new java.awt.Color(255, 101, 101));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_maintenance_20px.png"))); // NOI18N
        jButton2.setText("Đang Sửa Chữa");
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setIconTextGap(10);
        jButton2.setOpaque(true);
        jPanel35.add(jButton2);

        jPanel33.add(jPanel35);

        jPanel10.add(jPanel33, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel10);

        jPanel3.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new java.awt.BorderLayout());

        BlockItems.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BlockItemsLayout = new javax.swing.GroupLayout(BlockItems);
        BlockItems.setLayout(BlockItemsLayout);
        BlockItemsLayout.setHorizontalGroup(
            BlockItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1248, Short.MAX_VALUE)
        );
        BlockItemsLayout.setVerticalGroup(
            BlockItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(BlockItems);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(15, 502));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, java.awt.BorderLayout.WEST);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(15, 502));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7, java.awt.BorderLayout.EAST);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1250, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel8, java.awt.BorderLayout.SOUTH);

        jPanel3.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(jPanel3, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cboLoaiPhongMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboLoaiPhongMouseReleased

    }//GEN-LAST:event_cboLoaiPhongMouseReleased

    private void chkFilterTangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFilterTangItemStateChanged

    }//GEN-LAST:event_chkFilterTangItemStateChanged

    private void chkFilterTangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chkFilterTangMouseClicked
        if(!chkFilterTang.isSelected()){
            dcNgay.setEnabled(false);

        } else{
            dcNgay.setEnabled(true);
        }
    }//GEN-LAST:event_chkFilterTangMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.sortDataPhong();
        txtTenPhong.setText(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.openAddPhong();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnQuaHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuaHanActionPerformed
        this.openFunction();
    }//GEN-LAST:event_btnQuaHanActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
        this.updateRoomOverdue();
        this.loadBlock();
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void chkNgayItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkNgayItemStateChanged
        if(chkNgay.isSelected()){
            chkFinder.setEnabled(false);
        } else{
            chkFinder.setEnabled(true);
        }
    }//GEN-LAST:event_chkNgayItemStateChanged

    private void chkCMNDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkCMNDItemStateChanged
        if(!chkCMND.isSelected()){
            txtTenPhong.setEnabled(false);
            chkTimPhong.setSelected(false);
            if(chkFinder.isSelected()||chkNgay.isSelected()){
            chkFinder.setEnabled(true);
            chkTimPhong.setEnabled(true);chkTimPhong.setSelected(false);
            }else{
             chkFinder.setEnabled(true);
             chkNgay.setEnabled(true);
             chkTimPhong.setEnabled(true);chkTimPhong.setSelected(false);
            }
            chkFilterTang.setEnabled(true);
        } else{
            txtTenPhong.setEnabled(true);
            txtTenPhong.setText(null);
            chkFinder.setEnabled(false);
            chkNgay.setEnabled(false);
            chkFilterTang.setEnabled(false); 
            chkFinder.setSelected(false);
            chkNgay.setSelected(false);
            chkFilterTang.setSelected(false);
            chkTimPhong.setEnabled(false);
            chkTimPhong.setSelected(false);
        }
    }//GEN-LAST:event_chkCMNDItemStateChanged

    private void chkTimPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkTimPhongItemStateChanged
        if(!chkTimPhong.isSelected()){
            txtTenPhong.setEnabled(false);
            chkCMND.setEnabled(false);
            chkCMND.setSelected(false);
            if(chkFinder.isSelected()||chkNgay.isSelected()){
            chkFinder.setEnabled(true);
            chkCMND.setEnabled(true);
            chkCMND.setSelected(false);
            }else{
             chkFinder.setEnabled(true);
             chkNgay.setEnabled(true);
             chkCMND.setEnabled(true);
            chkCMND.setSelected(false);
            }
            chkFilterTang.setEnabled(true);
        } else{
            txtTenPhong.setEnabled(true);
            txtTenPhong.setText(null);
            chkFinder.setEnabled(false);
            chkNgay.setEnabled(false);
            chkFilterTang.setEnabled(false); 
            chkFinder.setSelected(false);
            chkNgay.setSelected(false);
            chkFilterTang.setSelected(false);
            chkCMND.setEnabled(true);
            chkCMND.setSelected(false);
        }
    }//GEN-LAST:event_chkTimPhongItemStateChanged

    private void chkFinderItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkFinderItemStateChanged
        if(chkFinder.isSelected()){
            chkNgay.setEnabled(false);
        } else{
            chkNgay.setEnabled(true);
        }
    }//GEN-LAST:event_chkFinderItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BlockItems;
    private javax.swing.ButtonGroup btnGR;
    public static javax.swing.JButton btnQuaHan;
    public static javax.swing.JButton btnShowAll;
    private javax.swing.JComboBox<String> cboLoaiPhong;
    private javax.swing.JComboBox<String> cboTang;
    private javax.swing.JCheckBox chkCMND;
    private javax.swing.JCheckBox chkFilterTang;
    private javax.swing.JCheckBox chkFinder;
    private javax.swing.JCheckBox chkNgay;
    private javax.swing.JCheckBox chkTimPhong;
    private com.toedter.calendar.JDateChooser dcNgay;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtTenPhong;
    // End of variables declaration//GEN-END:variables

    // Load Blocks
    public void loadBlock(){
        BlockItems.removeAll();
        List<Model_Phong> list = this.dao.select();
        
        for (Model_Phong mdl:list){ 
            String ten="";
            String ngayNhan="";
            String ngayTra="";
            String maPhong = mdl.getMaPhong();
            String tenPhong = mdl.getTenPhong();
            int trangThai = mdl.getTrangThai();
            int maLoaiPhong = Integer.parseInt(mdl.getMaLoaiPhong());
            Model_PhieuDangKy listDK = this.dkdao.findByMaPhongActive3(mdl.getMaPhong());
            if(listDK!=null){
            int maKH = listDK.getMaKH();
            Model_KhachHang listKH = this.khdao.findById(maKH);
            ten = listKH.getHoTen();
            ngayNhan = DateHelper.toString(listDK.getNgayNhanPhong(), new String[0]);
            ngayTra = String.valueOf(DateHelper.toString(listDK.getNgayTraPhongDuKien(), new String[0]));
          
            }
            BlockItems.add(new BlockPhong(maPhong,tenPhong,trangThai,maLoaiPhong,ten,ngayNhan,ngayTra));
            BlockItems.repaint();
            BlockItems.revalidate();
            
        }
    }
    
  //Load ComboBox : Tầng
    private void loadTang(){
        DefaultComboBoxModel cboMdl = (DefaultComboBoxModel)this.cboTang.getModel();
        cboMdl.removeAllElements();
        List list = this.dao.selectTang();
        for (int i=0;i<list.size();i++) {
                String tang = list.get(i).toString();
                    cboMdl.addElement(tang);     
            }
    }
  //Load ComboBox : Loại Phòng
    private void loadLoaiPhong(){
        DefaultComboBoxModel cboMdl = (DefaultComboBoxModel)this.cboLoaiPhong.getModel();
        cboMdl.removeAllElements();
        List<Model_LoaiPhong> list = this.lpdao.select();
        for (Model_LoaiPhong mdl:list){
            String loai = mdl.getTenLP();
            cboMdl.addElement(loai);
        }
    }
    //Sort Data
    public void sortDataPhong(){
        String tang = String.valueOf(cboTang.getSelectedItem());    
        String tenloai = String.valueOf(cboLoaiPhong.getSelectedItem());
        List<Model_LoaiPhong> lp = this.lpdao.findExactKeyword(tenloai);
        String loai= String.valueOf(lp.get(0).getMaLP());
        String ngay = String.valueOf(DateHelper.toString(dcNgay.getDate(), new String[0]));
        
        //TANG & FINDER CHECKED
        if(chkFilterTang.isSelected()&&chkFinder.isSelected()){
            List<Model_Phong> list = (List<Model_Phong>) this.dao.sortData(tang,loai,null,null,2);
            if(list!=null){
            this.loadBlockSorted(list);
            } else{
                DialogHelper.alert(this, "Không có kết quả!");
                this.loadBlock();
            }
        }else //TANG CHECKED
        if(chkFilterTang.isSelected()){
            List<Model_Phong> list = (List<Model_Phong>) this.dao.sortData(tang,loai,null,null,1);
            if(list!=null){
            this.loadBlockSorted(list);
            } else {
                this.loadBlock();
                DialogHelper.alert(this, "Không có kết quả!");  
            }
        }else
        //NGAY & FINDER CHECKED
//        if(chkNgay.isSelected()&&chkFinder.isSelected()){
//            List<Model_Phong> list = (List<Model_Phong>) this.dao.sortData(null,loai,ngay,null,4);
//            if(list!=null){
//            this.loadBlockSorted(list);
//            } else{
//                DialogHelper.alert(this, "Không có kết quả!");
//                this.loadBlock();
//            }
//        }else
        //NGAY CHECKED  
        if(chkNgay.isSelected()){
            List<Model_Phong> list = (List<Model_Phong>) this.dao.sortData(null,loai,ngay,null,3);
            if(list!=null){
            this.loadBlockSorted(list);
            } else{
                DialogHelper.alert(this, "Không có kết quả!");
                this.loadBlock();
            }
        }else      
        //NGAY, TANG & FINDER CHECKED  
//        if(chkNgay.isSelected()&&chkFilterTang.isSelected()&&chkFinder.isSelected()){
//            List<Model_Phong> list = (List<Model_Phong>) this.dao.sortData(tang,loai,ngay,null,6);
//            if(list!=null){
//            this.loadBlockSorted(list);
//            } else{
//                DialogHelper.alert(this, "Không có kết quả!");
//                this.loadBlock();
//            }  
//        }else
        //NGAY & TANG CHECKED
        if(chkNgay.isSelected()&&chkFilterTang.isSelected()){
            List<Model_Phong> list = (List<Model_Phong>) this.dao.sortData(tang,loai,ngay,null,5);
            if(list!=null){
            this.loadBlockSorted(list);
            } else{
                DialogHelper.alert(this, "Không có kết quả!");
                this.loadBlock();
            }                    
        }else
        //TEXT ARE FILLED AND ROOM NAME CHECKED
        if((!txtTenPhong.getText().isEmpty()||txtTenPhong.getText()!="")&&chkTimPhong.isSelected()){
            String keyword = txtTenPhong.getText();
            List<Model_Phong> list = (List<Model_Phong>) this.dao.sortData(null,null,null,keyword,8);
            if(list!=null){
            this.loadBlockSorted(list);
            } else{
                DialogHelper.alert(this, "Không có kết quả!");
                this.loadBlock();
            }           
        }else //TEXT ARE FILLED AND PERSONAL ID CHECKED
            if((!txtTenPhong.getText().isEmpty()||txtTenPhong.getText()!="")&&chkCMND.isSelected()){
            String keyword = txtTenPhong.getText();
            List<Model_Phong> list = (List<Model_Phong>) this.dao.sortData(null,null,null,keyword,9);
            if(list!=null){
            this.loadBlockSorted(list);
            } else{
                DialogHelper.alert(this, "Không có kết quả!");
                this.loadBlock();
            }           
        }else   
        //FINDER CHECKED
        if(chkFinder.isSelected()){
            List<Model_Phong> list = (List<Model_Phong>) this.dao.sortData(null,loai,null,null,7);
            if(list!=null){
            this.loadBlockSorted(list);
            } else{
                DialogHelper.alert(this, "Không có kết quả!");
                this.loadBlock();
            }           
        }else{
            //NO BOX CHECKED
            List<Model_Phong> list =(List<Model_Phong>) this.dao.sortData(null,loai,null,null,0);
            if(list!=null){
            this.loadBlockSorted(list);
            } else{
                DialogHelper.alert(this,"Không có kết quả!");
                this.loadBlock();
            }
        }
    }
    //Load Sorted Blocks
    private void loadBlockSorted(List<Model_Phong> list){
        BlockItems.removeAll();
        List<Model_Phong> lists = list;
        for (Model_Phong mdl:lists){ 
            String ten="";
            String ngayNhan="";
            String ngayTra="";
            String maPhong = mdl.getMaPhong();
            String tenPhong = mdl.getTenPhong();
            int trangThai = mdl.getTrangThai();
            int maLoaiPhong = Integer.parseInt(mdl.getMaLoaiPhong());
            Model_PhieuDangKy listDK = this.dkdao.findByMaPhongActive3(mdl.getMaPhong());
            if(listDK!=null){
            int maKH = listDK.getMaKH();
            Model_KhachHang listKH = this.khdao.findById(maKH);
            ten = listKH.getHoTen();
            ngayNhan = DateHelper.toString(listDK.getNgayNhanPhong(), new String[0]);
            ngayTra = String.valueOf(DateHelper.toString(listDK.getNgayTraPhongDuKien(), new String[0]));
            
            }

            BlockItems.add(new BlockPhong(maPhong,tenPhong,trangThai,maLoaiPhong,ten,ngayNhan,ngayTra));
            BlockItems.repaint();
            BlockItems.revalidate();
            }
        }        
    //Open Thêm Phòng    
    void openAddPhong() {
        ThemPhong jd = new ThemPhong(new javax.swing.JFrame(), true);
        jd.setVisible(true);
        jd.setModal(true);
        jd.setAlwaysOnTop(true);
        jd.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
       
    }
    //Open Menu Function
    void openFunction() {
        MenuChucNang jd = new MenuChucNang(new javax.swing.JFrame(), true);
        jd.setVisible(true);
        jd.setModal(true);
        jd.setAlwaysOnTop(true);
        jd.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
       
    }
    
     private void updateRoomOverdue(){
        try {
            List<Model_PhieuDangKy> list = this.dkdao.selectbyOverdueRoom();
            if(list!=null){
            for (Model_PhieuDangKy pdk : list) {
                Model_Phong mdl = this.dao.findById(String.valueOf(pdk.getMaPhong()));
                mdl.setTrangThai(3);
                this.dao.update(mdl);
                }  
            }
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn CSDL!");
            e.printStackTrace();
        }
    }
}
