/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI;

import com.team3.DAO.DAO_HoaDon;
import com.team3.DAO.DAO_HoaDonChiTiet;
import com.team3.DAO.DAO_LoaiPhong;
import com.team3.DAO.DAO_PhieuDangKy;
import com.team3.DAO.DAO_Phong;
import com.team3.Helpers.DialogHelper;
import com.team3.Helpers.ShareHelper;
import com.team3.Model.Model_HoaDon;
import com.team3.Model.Model_HoaDonChiTiet;
import com.team3.Model.Model_LoaiPhong;
import com.team3.Model.Model_PhieuDangKy;
import com.team3.Model.Model_Phong;
import com.team3.UI.JPanel.SoDoPhong;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Dell Vostro
 */
public class ChinhSuaPhong extends javax.swing.JDialog {
    DAO_LoaiPhong lpdao = new DAO_LoaiPhong();
    DAO_Phong pDao = new DAO_Phong();
    String masoPhong;
    static int xx, yy;
    
    /**
     * Creates new form PhieuDangKy
     */
    public ChinhSuaPhong(java.awt.Frame parent, boolean modal,String maSoPhong, String tenPhong) {
        super(parent, modal);
        masoPhong = maSoPhong;
        initComponents();
        lblTitle.setText("Chỉnh sửa phòng: "+tenPhong);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblIconApp = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTrangThaiPhong = new javax.swing.JLabel();
        txtTang = new javax.swing.JTextField();
        btnXoaPhong = new javax.swing.JButton();
        cboLoaiPhong = new javax.swing.JComboBox<>();
        txtTenPhong = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        btnCapnhat = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        jMenuItem1.setText("Xem/Sửa Phiếu");
        jPopupMenu1.add(jMenuItem1);
        jPopupMenu1.add(jSeparator1);

        jMenuItem2.setText("Thoát");
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(48, 55, 79));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblCloseAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 30, 30));

        lblIconApp.setBackground(new java.awt.Color(153, 255, 102));
        lblIconApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/iconApp.png"))); // NOI18N
        lblIconApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lblIconApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Chỉnh sửa phòng: P205");
        jPanel2.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 270, 30));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 370, 30);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setComponentPopupMenu(jPopupMenu1);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tên phòng");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ghi chú");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Loại phòng");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Tầng");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        lblTrangThaiPhong.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTrangThaiPhong.setText("Trạng thái");
        jPanel3.add(lblTrangThaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 200, -1));

        txtTang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTang.setEnabled(false);
        jPanel3.add(txtTang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 330, -1));

        btnXoaPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoaPhong.setText("Xóa phòng này");
        btnXoaPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaPhongActionPerformed(evt);
            }
        });
        jPanel3.add(btnXoaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 130, 30));

        cboLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(cboLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 330, 30));

        txtTenPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenPhong.setEnabled(false);
        jPanel3.add(txtTenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 330, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Trạng thái");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGhiChu.setRows(5);
        jScrollPane1.setViewportView(txtGhiChu);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 330, 80));

        btnCapnhat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCapnhat.setText("Cập nhật");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });
        jPanel3.add(btnCapnhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 130, 30));

        btnBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBack.setText("Quay Lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel3.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 130, 30));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 30, 370, 510);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close2.png")));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close.png")));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        this.dispose();
    }//GEN-LAST:event_lblCloseMousePressed

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void btnXoaPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaPhongActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaPhongActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.goBack();
    }//GEN-LAST:event_btnBackActionPerformed

    private void lblCloseAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblCloseAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCloseAncestorAdded

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.goBack();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        this.update();
    }//GEN-LAST:event_btnCapnhatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChinhSuaPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                ChinhSuaPhong dialog = new ChinhSuaPhong(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnXoaPhong;
    private javax.swing.JComboBox<String> cboLoaiPhong;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblIconApp;
    public static javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTrangThaiPhong;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtTang;
    private javax.swing.JTextField txtTenPhong;
    // End of variables declaration//GEN-END:variables
    
    void init(){
        this.setIconImage((ShareHelper.APP_ICON));
        this.loadLoaiPhong();
        this.loadDatatoForm();
    }
    private void loadLoaiPhong(){
        DefaultComboBoxModel cboMdl = (DefaultComboBoxModel)this.cboLoaiPhong.getModel();
        cboMdl.removeAllElements();
        List<Model_LoaiPhong> list = this.lpdao.select();
        for (Model_LoaiPhong mdl:list){
            String loai = mdl.getTenLP();
            cboMdl.addElement(loai);
        }
    }
    private void loadDatatoForm(){
        Model_Phong mdl = this.pDao.findById(masoPhong); 
        Model_LoaiPhong mdllp = this.lpdao.findById(mdl.getMaLoaiPhong());
        String tenLoai = mdllp.getTenLP();
        txtTenPhong.setText(mdl.getTenPhong());
        txtTang.setText(mdl.getTang());
        txtGhiChu.setText(mdl.getGhiChu());
        switch(mdl.getTrangThai()){
            case 0:
            lblTrangThaiPhong.setText("Phòng Trống");
            break;
            case 1:
            lblTrangThaiPhong.setText("Khách Đang Dùng");
            break;
            case 2:
            lblTrangThaiPhong.setText("Phong Đang Bẩn");
            break;
            case 3:
            lblTrangThaiPhong.setText("Phòng có khách sắp đi");
            break;
            case 4:
            lblTrangThaiPhong.setText("Phòng đang sửa chữa");
            break;
            case 5:
            lblTrangThaiPhong.setText("Phòng đang được đặt trước");
            break;
        }
        cboLoaiPhong.setSelectedItem(tenLoai);
    }
    void delete(){
        Model_Phong mdl = this.pDao.findById(masoPhong);
            switch(mdl.getTrangThai()){
            case 0:
            this.deleteAction();
            break;
            case 1:
            DialogHelper.alert(this, "Bạn không được xóa phòng đang có khách!");
            break;
            case 2:
            this.deleteAction();
            break;
            case 3:
            DialogHelper.alert(this, "Bạn không được xóa phòng đang có khách!");
            break;
            case 4:
            this.deleteAction();
            break;
            case 5:
            DialogHelper.alert(this, "Bạn không được xóa phòng đang được đặt trước!");
            break;
        }
        
    }
    void deleteAction(){
        if (DialogHelper.confirm(this, "Xóa phòng sẽ xóa cả những dữ liệu liên quan, tiếp tục?")) {
            try {
                DAO_HoaDon hddao = new DAO_HoaDon();
                DAO_HoaDonChiTiet hdctdao = new DAO_HoaDonChiTiet();
                DAO_PhieuDangKy pdkdao = new DAO_PhieuDangKy();
                Model_PhieuDangKy mdlpdk = pdkdao.findByMaPhong(masoPhong);
                if(mdlpdk!=null){
                Model_HoaDon mdlhd = hddao.findByMaPDK(mdlpdk.getMaPhieuDK());
                Model_HoaDonChiTiet mdlhdct = hdctdao.findByMaHD(mdlhd.getMaHD());
                hdctdao.deletea(mdlhdct.getMaHD());
                hddao.delete(mdlhd.getMaHD());
                pdkdao.delete(mdlpdk.getMaPhieuDK());
                pDao.delete(masoPhong);
                }else{
                pDao.delete(masoPhong);}
                DialogHelper.alert(this, "Xóa thành công!");
                
                this.dispose();
                SoDoPhong.btnShowAll.doClick();
            } catch (Exception e) {
                DialogHelper.alert(this, "Xóa thất bại!");
                e.printStackTrace();
            }
        }
    }
    void goBack(){
       if(txtGhiChu.getText().length()>0){
           if(DialogHelper.confirm(this, "Dữ liệu dang chỉnh sửa, bạn có thực sự muốn thoát?")){
               
           this.dispose();
           SoDoPhong.btnShowAll.doClick();
           }
       } else{
           
           this.dispose();
           SoDoPhong.btnShowAll.doClick();
       }
   } 
    void update() {
        Model_Phong model = getModel();
        try {
            pDao.update(model); 
            DialogHelper.alert(this, "Cập nhật thành công!");
            SoDoPhong.btnShowAll.doClick();
            this.dispose();
        } catch (Exception e) {
            DialogHelper.alert(this, "Cập nhật thất bại!");
            e.printStackTrace();
        }
    }
    Model_Phong getModel() {
        Model_Phong model = new Model_Phong();
        model.setMaPhong(masoPhong);
        model.setTang(txtTang.getText());
        model.setTenPhong(txtTenPhong.getText());
        List<Model_LoaiPhong> mdllp = this.lpdao.findExactKeyword(cboLoaiPhong.getSelectedItem().toString());        
        model.setMaLoaiPhong(String.valueOf(mdllp.get(0).getMaLP()));
        model.setGhiChu(txtGhiChu.getText());
        Model_Phong mdl = this.pDao.findById(masoPhong); 
        model.setTrangThai(mdl.getTrangThai());
        return model;
    }
}
