/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI;

import com.team3.DAO.DAO_KhachHang;
import com.team3.DAO.DAO_PhieuDangKy;
import com.team3.DAO.DAO_Phong;
import com.team3.Helpers.DialogHelper;
import com.team3.Model.Model_PhieuDangKy;
import com.team3.Model.Model_Phong;
import com.team3.UI.JPanel.SoDoPhong;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;

/**
 *
 * @author Dell Vostro
 */
public class ChuyenPhong extends javax.swing.JDialog {
    DAO_PhieuDangKy dkdao = new DAO_PhieuDangKy();
    DAO_Phong pDao = new DAO_Phong();
    DAO_KhachHang khdao = new DAO_KhachHang();
    String maPhong;
    int trangthai;
    static int xx, yy;
    /**
     * Creates new form ChuyenPhong
     */
    public ChuyenPhong(java.awt.Frame parent, boolean modal, String masoPhong, int trangThai) {
        super(parent, modal);
        initComponents();
        this.loadListAvailable();
        maPhong = masoPhong;
        trangthai = trangThai;
        this.loadCurrentUse();
    }
    public ChuyenPhong(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.loadListAvailable();
        this.loadCurrentUse();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblClose3 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblIconApp = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsDangDung = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsConTrong = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSwap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(48, 55, 79));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close.png"))); // NOI18N
        lblClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClose3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClose3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblClose3MousePressed(evt);
            }
        });
        jPanel5.add(lblClose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 30, 30));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Chuyển đổi phòng");
        jPanel5.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 620, 30));

        lblIconApp.setBackground(new java.awt.Color(153, 255, 102));
        lblIconApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/iconApp.png"))); // NOI18N
        lblIconApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(lblIconApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 55, 79)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lsDangDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lsDangDung.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lsDangDung);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 230, 230));

        lsConTrong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lsConTrong.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lsConTrong);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 230, 230));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Phòng đang dùng");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Phòng còn trống");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 230, 30));

        btnSwap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/0000.png"))); // NOI18N
        btnSwap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSwapActionPerformed(evt);
            }
        });
        jPanel6.add(btnSwap, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 80, 50));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 700, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseClicked
        this.dispose();
    }//GEN-LAST:event_lblClose3MouseClicked

    private void lblClose3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseEntered
        lblClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close2.png")));
    }//GEN-LAST:event_lblClose3MouseEntered

    private void lblClose3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseExited
        lblClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close.png")));
    }//GEN-LAST:event_lblClose3MouseExited

    private void lblClose3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MousePressed
        this.dispose();
    }//GEN-LAST:event_lblClose3MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void btnSwapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSwapActionPerformed
        if(lsDangDung.getSelectedIndex()<0||lsConTrong.getSelectedIndex()<0){
            DialogHelper.alert(this, "Bạn chưa chọn phòng cần đổi!");
        } else{
        this.swap();
        }
    }//GEN-LAST:event_btnSwapActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChuyenPhong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChuyenPhong dialog = new ChuyenPhong(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSwap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClose3;
    private javax.swing.JLabel lblIconApp;
    public static javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lsConTrong;
    private javax.swing.JList<String> lsDangDung;
    // End of variables declaration//GEN-END:variables
    private void loadListAvailable(){
        
        DefaultListModel model = new DefaultListModel();    
        model.removeAllElements();
        try {
            List<Model_Phong> list = this.pDao.sortData(null, null, null, null, 10);
            if(list!=null){
            for (Model_Phong p : list) {
                model.addElement(p.getTenPhong());
                lsConTrong.setModel(model);
                }  
            }
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn CSDL!");
            e.printStackTrace();
        }
    }
    private void loadCurrentUse(){
        DefaultListModel model = new DefaultListModel();    
        model.removeAllElements();
        try {
            Model_Phong mdl = this.pDao.findById(maPhong);
            if(mdl!=null){
                model.addElement(mdl.getTenPhong());
                lsDangDung.setModel(model);
                lsDangDung.setSelectionInterval(0, 0);
                }  
            }
        catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn CSDL!");
            e.printStackTrace();
        }
    }
    void swap(){
        try{
        ListModel lModel = lsDangDung.getModel();
        String oldRoom = lModel.getElementAt(lsDangDung.getSelectedIndex()).toString();
        ListModel lModel2 = lsConTrong.getModel();
        String newRoom = lModel2.getElementAt(lsConTrong.getSelectedIndex()).toString();
        Model_Phong mdlop = this.pDao.findByName(oldRoom);
        Model_Phong mdlnp = this.pDao.findByName(newRoom);
        Model_PhieuDangKy mdlpdk1 = this.dkdao.findByMaPhongActive(mdlop.getMaPhong());
        mdlpdk1.setMaPhong(Integer.valueOf(mdlnp.getMaPhong()));
        mdlnp.setTrangThai(mdlop.getTrangThai());
        mdlop.setTrangThai(2);
        this.pDao.update(mdlnp);
        this.pDao.update(mdlop);
        this.dkdao.update(mdlpdk1);
        DialogHelper.alert(this, "Chuyển đổi thành công!");
        this.dispose();
        SoDoPhong.btnShowAll.doClick();
    }
        catch(Exception e){
        DialogHelper.alert(this, "Lỗi truy vấn CSDL!");
            e.printStackTrace();
        }        
    }
}
