/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI;

import com.team3.DAO.DAO_HoaDon;
import com.team3.DAO.DAO_HoaDonChiTiet;
import com.team3.DAO.DAO_HoaDonTamTinh;
import com.team3.DAO.DAO_KhachHang;
import com.team3.DAO.DAO_LoaiPhong;
import com.team3.DAO.DAO_MaKhuyenMai;
import com.team3.DAO.DAO_PhieuDangKy;
import com.team3.DAO.DAO_Phong;
import com.team3.Helpers.ConnectorJDBC;
import com.team3.Helpers.DateHelper;
import com.team3.Helpers.DialogHelper;
import com.team3.Model.Model_HoaDon;
import com.team3.Model.Model_HoaDonChiTiet;
import com.team3.Model.Model_HoaDonTamTinh;
import com.team3.Model.Model_KhachHang;
import com.team3.Model.Model_LoaiPhong;
import com.team3.Model.Model_MaKhuyenMai;
import com.team3.Model.Model_PhieuDangKy;
import com.team3.Model.Model_Phong;
import com.team3.UI.JPanel.SoDoPhong;
import java.sql.Connection;
import java.sql.DriverManager;
import java.text.DecimalFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Hashtable;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dell Vostro
 */
public class HoaDonThanhToan extends javax.swing.JDialog {

    // DAO
    DAO_PhieuDangKy pdkdao = new DAO_PhieuDangKy();
    DAO_KhachHang khdao = new DAO_KhachHang();
    DAO_HoaDon hddao = new DAO_HoaDon();
    DAO_Phong pdao = new DAO_Phong();
    DAO_LoaiPhong lpdao = new DAO_LoaiPhong();
    DAO_MaKhuyenMai mkmdao = new DAO_MaKhuyenMai();
    DAO_HoaDonChiTiet hdctdao = new DAO_HoaDonChiTiet();
    DAO_HoaDonTamTinh hdttdao = new DAO_HoaDonTamTinh();
    DecimalFormat df = new DecimalFormat("0.##");

    // Thông tin phòng
    int maphong;
    String tenphong;
    String tenloaiphong;
    String trangthaiphong;
    double gialoaiphong;
    int masoPDK;

    // Thông tin khách hàng
    int makhachhang;
    String tenkhachhang;
    String cmnd;
    String sdt;
    String email;
    String diachi;

    // Thông tin hoá đơn
    int mahd;
    double tiendatcoc;
    double tongtien;

    //Thông tin phiếu đăng ký
    int maphieudangky;
    int trangthaiphieu;
    String ngaynhanphong;
    String ngaythanhtoan;

    // Thông tin mã khuyến mãi
    Date thoihan;
    double giamakhuyenmai;
    int trangthaimakm;
    String makhuyenmai;

    // Thông tin dịch vị
    double giadichvu;

    // Thông tin thanh toán
    int ngaynhan;
    int ngaydukien;
    int ngaytra;
    int sophuttra;
    int gioquydinh = 12;
    double phantrammoiphut = 0.166666667;
    int giotraphong;
    int sogiovuotgioihan;
    int ngayvuotgioihan;

    int index = 0;
    static int xx, yy;

    /**
     * Creates new form HoaDonThanhToan
     */
//    public HoaDonThanhToan(java.awt.Frame parent, boolean modal) {
//        super(parent, modal);
//        initComponents();
//    }
    public HoaDonThanhToan(java.awt.Frame parent, boolean modal, int maPDK) {
        super(parent, modal);
        initComponents();
        init();
        masoPDK = maPDK;
        edit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblClose = new javax.swing.JLabel();
        lblIconApp = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblIconApp1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JLabel();
        txtLoaiPhong = new javax.swing.JLabel();
        txtGiaPhong = new javax.swing.JLabel();
        txtGiaDV = new javax.swing.JLabel();
        dccNgayNhan = new javax.swing.JLabel();
        txtTienDatCoc = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTenKH = new javax.swing.JLabel();
        txtSDT = new javax.swing.JLabel();
        txtCMND = new javax.swing.JLabel();
        txtEmail = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDiaChi = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JLabel();
        dccNgayThanhToan = new javax.swing.JLabel();
        rdoTienMat = new javax.swing.JRadioButton();
        rdoCredit = new javax.swing.JRadioButton();
        txtMaKM = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txtTongTien = new javax.swing.JLabel();
        btnThanhToan = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(48, 55, 79));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel2.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 30, 30));

        lblIconApp.setBackground(new java.awt.Color(153, 255, 102));
        lblIconApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lblIconApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Hóa đơn thanh toán");
        jPanel2.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 270, 30));

        lblIconApp1.setBackground(new java.awt.Color(153, 255, 102));
        lblIconApp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconApp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/iconApp.png"))); // NOI18N
        lblIconApp1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(lblIconApp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tên phòng:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Loại phòng:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Giá phòng:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Giá dịch vụ:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Ngày nhận:");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tiền trả trước:");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        txtTenPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenPhong.setText("jLabel7");
        jPanel4.add(txtTenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 110, -1));

        txtLoaiPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtLoaiPhong.setText("jLabel8");
        jPanel4.add(txtLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, -1));

        txtGiaPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGiaPhong.setText("jLabel9");
        jPanel4.add(txtGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 110, -1));

        txtGiaDV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGiaDV.setText("jLabel10");
        jPanel4.add(txtGiaDV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, -1));

        dccNgayNhan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dccNgayNhan.setText("jLabel11");
        jPanel4.add(dccNgayNhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 110, -1));

        txtTienDatCoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTienDatCoc.setText("jLabel12");
        jPanel4.add(txtTienDatCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 110, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 300, 250));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        tblHoaDonChiTiet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hoá đơn", "Mã dịch vụ", "Tên", "Số lượng", "Đơn giá", "Tổng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDonChiTiet.setRowHeight(20);
        tblHoaDonChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonChiTietMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblHoaDonChiTiet);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 200));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 630, 210));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Tên khách hàng:");
        jPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("CMND:");
        jPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("SĐT:");
        jPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Email:");
        jPanel7.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Địa chỉ:");
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        txtTenKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtTenKH.setText("jLabel24");
        jPanel7.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 210, -1));

        txtSDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSDT.setText("jLabel25");
        jPanel7.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 160, -1));

        txtCMND.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCMND.setText("jLabel26");
        jPanel7.add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 170, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEmail.setText("jLabel27");
        jPanel7.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 170, -1));

        jScrollPane1.setBorder(null);

        txtDiaChi.setColumns(20);
        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDiaChi.setRows(5);
        txtDiaChi.setText("jLabel");
        jScrollPane1.setViewportView(txtDiaChi);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 480, 40));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 630, 160));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Mã hóa đơn:");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Ngày thanh toán:");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Hình thức thanh toán:");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Mã khuyến mãi:");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txtMaHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaHD.setText("jLabel7");
        jPanel8.add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 110, -1));

        dccNgayThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dccNgayThanhToan.setText("jLabel8");
        jPanel8.add(dccNgayThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, -1));

        rdoTienMat.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoTienMat);
        rdoTienMat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoTienMat.setText("Tiền mặt");
        jPanel8.add(rdoTienMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        rdoCredit.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rdoCredit);
        rdoCredit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rdoCredit.setText("Credit Cart");
        jPanel8.add(rdoCredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        txtMaKM.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel8.add(txtMaKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 180, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 300, 250));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 320, 40));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Thành tiền");
        jPanel9.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 2, 100, 30));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 670, 120, 40));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        txtTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTongTien.setText("label");
        jPanel10.add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 160, 40));

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 670, 180, 40));

        btnThanhToan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        jPanel3.add(btnThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 720, 140, 40));

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jPanel3.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 720, 140, 40));

        btnPrint.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 140, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 670, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close2.png")));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close.png")));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        this.dispose();
    }//GEN-LAST:event_lblCloseMousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        boolean result = DialogHelper.confirm(this, "Bạn có muốn thanh toán hoá đơn này?");
        if (result == true) {
            printBill();          
            this.dispose();
            SoDoPhong.btnShowAll.doClick();
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        checkMKM();
        ThanhToan();
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        insertHDTT();
        ConnectorJDBC.inHoaDon(masoPDK);
    }//GEN-LAST:event_btnPrintActionPerformed

    private void tblHoaDonChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonChiTietMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblHoaDonChiTietMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                HoaDonThanhToan dialog = new HoaDonThanhToan(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dccNgayNhan;
    private javax.swing.JLabel dccNgayThanhToan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblIconApp;
    private javax.swing.JLabel lblIconApp1;
    public static javax.swing.JLabel lblTitle;
    private javax.swing.JRadioButton rdoCredit;
    private javax.swing.JRadioButton rdoTienMat;
    private javax.swing.JTable tblHoaDonChiTiet;
    private javax.swing.JLabel txtCMND;
    private javax.swing.JTextArea txtDiaChi;
    private javax.swing.JLabel txtEmail;
    private javax.swing.JLabel txtGiaDV;
    private javax.swing.JLabel txtGiaPhong;
    private javax.swing.JLabel txtLoaiPhong;
    private javax.swing.JLabel txtMaHD;
    private javax.swing.JTextField txtMaKM;
    private javax.swing.JLabel txtSDT;
    private javax.swing.JLabel txtTenKH;
    private javax.swing.JLabel txtTenPhong;
    private javax.swing.JLabel txtTienDatCoc;
    private javax.swing.JLabel txtTongTien;
    // End of variables declaration//GEN-END:variables

    void init() {
        clear();
    }

    void edit() {
        getThongTin();
        setThongTin();
        GetDayandTime();
        ThanhToan();
    }

    void loadHDCT(int mahd) {
        DefaultTableModel model = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        model.setRowCount(0);
        try {
            List<Model_HoaDonChiTiet> list = hdctdao.selectHDCTandDV(mahd);
            if (list != null) {
                for (Model_HoaDonChiTiet hdct : list) {
                    Object[] row = new Object[]{
                        hdct.getMaHD(),
                        hdct.getMaDV(),
                        hdct.getTendv(),
                        hdct.getSoLuong(),
                        df.format(hdct.getDongia()),
                        df.format(hdct.getSoLuong() * hdct.getDongia()),};
                    model.addRow(row);
                }
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liếu");
        }
    }

    void clear() {
        rdoTienMat.setSelected(true);
        txtTenPhong.setText("");
        txtLoaiPhong.setText("");
        txtGiaPhong.setText("");
        txtGiaDV.setText("");
        dccNgayNhan.setText("");
        dccNgayThanhToan.setText("");
        txtTienDatCoc.setText("");
        txtTenKH.setText("");
        txtCMND.setText("");
        txtSDT.setText("");
        txtEmail.setText("");
        txtDiaChi.setText("");
        txtMaHD.setText("");
        txtMaKM.setText("");
        txtTongTien.setText("");
    }

    void getThongTin() {
        int id = masoPDK;

        //Lấy thông tin phiếu đăng kí theo mã phiếu đăng ký      
        Model_PhieuDangKy pdk = pdkdao.findByIdActive(String.valueOf(id));
        ngaynhanphong = DateHelper.toString(pdk.getNgayNhanPhong(), "dd/MM/yyyy");
        ngaythanhtoan = DateHelper.toString(DateHelper.now(), "dd/MM/yyyy");

        //Lấy thông tin khách hàng theo mã khách hàng
        Model_KhachHang kh = khdao.findById(pdk.getMaKH());
        tenkhachhang = kh.getHoTen();
        cmnd = kh.getCmnd();
        sdt = kh.getSdt();
        email = kh.getEmail();
        diachi = kh.getDiaChi();

        //Lấy thông tin phòng
        Model_Phong phong = pdao.findById(String.valueOf(pdk.getMaPhong()));
        tenphong = phong.getTenPhong();
        trangthaiphong = String.valueOf(phong.getTrangThai());

        //Lấy thông tin loại phòng
        Model_LoaiPhong lp = lpdao.findById(phong.getMaLoaiPhong());
        tenloaiphong = lp.getTenLP();
        gialoaiphong = lp.getDonGia();

        //Lấy thông tin hoá đơn
        Model_HoaDon hd = hddao.findByMaPDK(pdk.getMaPhieuDK());
        mahd = hd.getMaHD();
        tiendatcoc = hd.getTongTien();
        hd.setNgayThanhToan(DateHelper.now());
        hddao.update(hd);

        //Lấy thông tin hoá đơn chi tiết
        loadHDCT(mahd);
        List<Model_HoaDonChiTiet> list = hdctdao.TongGiaDV(mahd);
        for (Model_HoaDonChiTiet hdct : list) {
            giadichvu = hdct.getTongtiendichvu();
        }
    }

    void setThongTin() {
        //Thông tin phiếu đăng ký
        dccNgayNhan.setText(ngaynhanphong);
        dccNgayThanhToan.setText(ngaythanhtoan);

        //Thông tin khách
        txtTenKH.setText(tenkhachhang);
        txtCMND.setText(cmnd);
        txtSDT.setText(sdt);
        txtEmail.setText(email);
        txtDiaChi.setText(diachi);

        //Thông tin phòng
        txtTenPhong.setText(tenphong);
        txtLoaiPhong.setText(tenloaiphong);
        txtGiaPhong.setText(df.format(gialoaiphong));

        //Thông tin hoá đơn
        txtMaHD.setText(String.valueOf(mahd));
        txtTienDatCoc.setText(String.valueOf(df.format(tiendatcoc)));
        txtGiaDV.setText(String.valueOf(df.format(giadichvu)));
    }

    void GetDayandTime() {
        int id = masoPDK;
        Model_PhieuDangKy pdk = pdkdao.findById(String.valueOf(id));
        Date date = DateHelper.now();

        Calendar cal = Calendar.getInstance();
        cal.setTime(date);
        Date pdkngaynhan = pdk.getNgayNhanPhong();
        Date pdkngaytradk = pdk.getNgayTraPhongDuKien();
        Calendar ca2 = Calendar.getInstance();
        ca2.setTime(pdkngaynhan);
        Calendar ca3 = Calendar.getInstance();
        ca3.setTime(pdkngaytradk);
        ngaynhan = ca2.get(Calendar.DATE);
        ngaydukien = ca3.get(Calendar.DATE);

        ngaytra = cal.get(Calendar.DATE);
        giotraphong = cal.get(Calendar.HOUR_OF_DAY);
        sophuttra = cal.get(Calendar.MINUTE);
        ThanhToan();
    }

    void ThanhToan() {
        if (ngaytra < ngaydukien) {
            if (giotraphong < gioquydinh) {
                if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                    tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * giamakhuyenmai / 100) - tiendatcoc + (gialoaiphong * 10 / 100) + giadichvu;
                } else if (giamakhuyenmai == 100) {
                    tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * 0) - tiendatcoc + (gialoaiphong * 10 / 100) + giadichvu;
                } else {
                    tongtien = (gialoaiphong * (ngaytra - ngaynhan)) - tiendatcoc + (gialoaiphong * 10 / 100) + giadichvu;
                }
            } else if (giotraphong == gioquydinh) {
                if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                    tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * giamakhuyenmai / 100) - tiendatcoc + (sophuttra * phantrammoiphut * gialoaiphong / 100) + (gialoaiphong * 10 / 100) + giadichvu;
                } else if (giamakhuyenmai == 100) {
                    tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * 0) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + (gialoaiphong * 10 / 100) + giadichvu;
                } else {
                    tongtien = (gialoaiphong * (ngaytra - ngaynhan)) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + (gialoaiphong * 10 / 100) + giadichvu;
                }
            } else if (giotraphong > gioquydinh) {
                if (giotraphong - gioquydinh <= 4) {
                    if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                        tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * giamakhuyenmai / 100) + ((giotraphong - gioquydinh) * gialoaiphong * 10 / 100) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else if (giamakhuyenmai == 100) {
                        tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * 0) + ((giotraphong - gioquydinh) * gialoaiphong * 10 / 100) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + (gialoaiphong * 10 / 100) + giadichvu;
                    } else {
                        tongtien = (gialoaiphong * (ngaytra - ngaynhan)) + ((giotraphong - gioquydinh) * gialoaiphong * 10 / 100) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + (gialoaiphong * 10 / 100) + giadichvu;
                    }
                } else {
                    if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                        tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * giamakhuyenmai / 100) + gialoaiphong + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else if (giamakhuyenmai == 100) {
                        tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * 0) + gialoaiphong + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else {
                        tongtien = (gialoaiphong * (ngaytra - ngaynhan)) + gialoaiphong + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    }
                }
            }
        }

        if (ngaytra == ngaydukien) {
            if (giotraphong < gioquydinh) {
                if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                    tongtien = (gialoaiphong * giamakhuyenmai / 100) - tiendatcoc + giadichvu;
                } else if (giamakhuyenmai == 100) {
                    tongtien = (gialoaiphong * 0) - tiendatcoc + giadichvu;
                } else {
                    tongtien = gialoaiphong - tiendatcoc + giadichvu;
                }
            } else if (giotraphong == gioquydinh) {
                if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                    tongtien = (gialoaiphong * giamakhuyenmai / 100) - tiendatcoc + (sophuttra * phantrammoiphut * gialoaiphong / 100) + giadichvu;
                } else if (giamakhuyenmai == 100) {
                    tongtien = (gialoaiphong * 0) + (sophuttra * phantrammoiphut * gialoaiphong / 100) + giadichvu;
                } else {
                    tongtien = gialoaiphong + (sophuttra * phantrammoiphut * gialoaiphong / 100) + giadichvu;
                }
            } else if (giotraphong > gioquydinh) {
                if (giotraphong - gioquydinh <= 4) {
                    if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                        tongtien = (gialoaiphong * giamakhuyenmai / 100) + ((giotraphong - gioquydinh) * gialoaiphong * 10 / 100) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else if (giamakhuyenmai == 100) {
                        tongtien = (gialoaiphong * 0) + ((giotraphong - gioquydinh) * gialoaiphong * 10 / 100) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else {
                        tongtien = gialoaiphong + ((giotraphong - gioquydinh) * gialoaiphong * 10 / 100) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    }
                } else {
                    if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                        tongtien = (gialoaiphong * giamakhuyenmai / 100) + gialoaiphong + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else if (giamakhuyenmai == 100) {
                        tongtien = (gialoaiphong * 0) + gialoaiphong + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else {
                        tongtien = gialoaiphong + gialoaiphong + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    }
                }
            }
        }

        if (ngaytra > ngaydukien) {
            if (giotraphong < gioquydinh) {
                if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                    tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * giamakhuyenmai / 100) - tiendatcoc + giadichvu;
                } else if (giamakhuyenmai == 100) {
                    tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * 0) - tiendatcoc + giadichvu;
                } else {
                    tongtien = (gialoaiphong * (ngaytra - ngaynhan)) - tiendatcoc + giadichvu;
                }
            } else if (giotraphong == gioquydinh) {
                if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                    tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * giamakhuyenmai / 100) - tiendatcoc + (sophuttra * phantrammoiphut * gialoaiphong / 100) + giadichvu;
                } else if (giamakhuyenmai == 100) {
                    tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * 0) + (sophuttra * phantrammoiphut * gialoaiphong / 100) + giadichvu;
                } else {
                    tongtien = (gialoaiphong * (ngaytra - ngaynhan)) + (sophuttra * phantrammoiphut * gialoaiphong / 100) + giadichvu;
                }
            } else if (giotraphong > gioquydinh) {
                if (giotraphong - gioquydinh <= 4) {
                    if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                        tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * giamakhuyenmai / 100) + ((giotraphong - gioquydinh) * gialoaiphong * 10 / 100) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else if (giamakhuyenmai == 100) {
                        tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * 0) + ((giotraphong - gioquydinh) * gialoaiphong * 10 / 100) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else {
                        tongtien = (gialoaiphong * (ngaytra - ngaynhan)) + ((giotraphong - gioquydinh) * gialoaiphong * 10 / 100) + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    }
                } else {
                    if (giamakhuyenmai > 0 && giamakhuyenmai < 100) {
                        tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * giamakhuyenmai / 100) + gialoaiphong + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else if (giamakhuyenmai == 100) {
                        tongtien = ((gialoaiphong * (ngaytra - ngaynhan)) * 0) + gialoaiphong + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    } else {
                        tongtien = (gialoaiphong * (ngaytra - ngaynhan)) + gialoaiphong + (sophuttra * phantrammoiphut * gialoaiphong / 100) - tiendatcoc + giadichvu;
                    }
                }
            }
        }
        txtTongTien.setText(String.valueOf(df.format(tongtien)));
    }

    void checkMKM() {
        if (txtMaKM.getText().length() > 0) {
            makhuyenmai = txtMaKM.getText();
            Model_MaKhuyenMai mkm = mkmdao.findByMa(makhuyenmai);
            if (mkm != null) {
                trangthaimakm = mkm.getTrangThai();
                if (trangthaimakm == 0) {
                    if (mkm.getGiaTri() > 0 && mkm.getGiaTri() < 100) {
                        giamakhuyenmai = mkm.getGiaTri();
                    } else if (mkm.getGiaTri() == 100) {
                        giamakhuyenmai = mkm.getGiaTri();
                    }
                } else {
                    DialogHelper.alert(this, "Mã đã hết hạn hoặc được sử dụng");
                    txtMaKM.requestFocus();
                    txtMaKM.setText("");
                }
            } else {
                DialogHelper.alert(this, "Mã khuyến mãi không tồn tại");
                txtMaKM.requestFocus();
                txtMaKM.setText("");
            }
        }
    }

    boolean checkMKMexist() {
        Model_MaKhuyenMai mkm = mkmdao.findByMa(txtMaKM.getText().trim());
        if (mkm != null) {
            if (mkm.getTrangThai() == 0) {
                return true;
            } else {
                DialogHelper.alert(this, "Mã khuyến mãi hết hạn hoặc đã được sử dụng");
                return false;
            }
        } else if (txtMaKM.getText() == "" || txtMaKM.getText().isEmpty()) {
            return true;
        } else {
            DialogHelper.alert(this, "Mã khuyến mãi không tồn tại");
            return false;
        }
    }

    void printBill() {
        if (checkMKMexist()) {
            //Cập nhật thông tin phòng khi thanh toán
            Model_Phong phong = pdao.findByName(txtTenPhong.getText().trim());
            phong.setTrangThai(2);
            pdao.update(phong);

            //Cập nhật thông tin phiếu đăng ký khi thanh toán
            Model_PhieuDangKy pdk = pdkdao.findByMaPhongActive(phong.getMaPhong());
            pdk.setNgayTraPhongThucTe(DateHelper.now());
            pdk.setTrangThai(1);
            pdkdao.update(pdk);

            //Cập nhật thông tin hoá đơn khi thanh toán
            Model_HoaDon hd = hddao.findByMaPDK(pdk.getMaPhieuDK());
            hd.setNgayThanhToan(DateHelper.now());
            if (rdoTienMat.isSelected()) {
                hd.setHinhThucThanhToan(0);
            } else {
                hd.setHinhThucThanhToan(1);
            }
            Model_MaKhuyenMai mkm = mkmdao.findByMa(txtMaKM.getText().trim());
            if (mkm != null) {
                mkm.setTrangThai(1);
                mkmdao.update(mkm);
                hd.setMaKM(txtMaKM.getText().trim());
                hd.setTongTien(tongtien);
                hd.setTrangThai(1);
                hddao.update(hd);
                DialogHelper.alert(this, "Thanh toán hoá đơn thành công");
            } else {
                hd.setMaKM(null);
                hd.setTongTien(tongtien);
                hd.setTrangThai(1);
                hddao.update(hd);
                DialogHelper.alert(this, "Thanh toán hoá đơn thành công");
            }

            //Xoá hoá đơn tạm tính khi thanh toán
            Model_HoaDonTamTinh hdtt = hdttdao.findByMaHD(mahd);
            if (hdtt != null) {
                hdttdao.delete(hdtt.getMaHD());
            }
        }
    }

    void insertHDTT() {
        Model_HoaDonTamTinh model = hdttdao.findByMaHD(mahd);
        if (model == null) {
            Model_HoaDonTamTinh hdtt = new Model_HoaDonTamTinh();
            hdtt.setMaHD(mahd);
            hdtt.setTongTien(tongtien);
            hdtt.setTrangThai(0);
            hdttdao.insert(hdtt);
        } else {

        }
    }

//    void inHoaDon(int mapdk) {
//        try {
//
//            String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
//            String dburl = "jdbc:sqlserver://localhost:1433;database=Quanlykhachsan";
//            String username = "sa";
//            String password = "songlong";
//            Class.forName(driver);
//            Connection con = DriverManager.getConnection(dburl, username, password);
//            ConnectorJDBC conn = new ConnectorJDBC();
//            Hashtable map = new Hashtable();
//            JasperReport file = JasperCompileManager.compileReport("src\\com\\team3\\UI\\report1.jrxml");
//            map.put("MaPhieuDK", mapdk);
//            JasperPrint print = JasperFillManager.fillReport(file, map, conn);
//            JasperViewer.viewReport(print, false);
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
}
