/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI;

import com.team3.Helpers.DialogHelper;
import com.team3.Helpers.ShareHelper;
import com.team3.UI.JPanel.*;
import java.awt.Color;
import java.awt.Dialog;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Dell Vostro
 */
public class MainForm extends javax.swing.JFrame {

    static int xx, yy;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuUser = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        TitleBar = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Actions = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        maximize = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        lblIconApp = new javax.swing.JLabel();
        Menus = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        Top = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblLogout = new javax.swing.JLabel();
        btnUser = new javax.swing.JToggleButton();
        Contents = new javax.swing.JPanel();
        Content = new javax.swing.JPanel();
        lblBG = new javax.swing.JLabel();
        Bottom = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblGioiThieu = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblDongHo = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblNgay = new javax.swing.JLabel();

        MenuUser.setBackground(new java.awt.Color(48, 55, 79));
        MenuUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        MenuUser.setBorder(null);

        jMenuItem1.setBackground(new java.awt.Color(48, 55, 79));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_male_user_20px.png"))); // NOI18N
        jMenuItem1.setText("Thông tin tài khoản");
        jMenuItem1.setContentAreaFilled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuUser.add(jMenuItem1);
        MenuUser.add(jSeparator1);

        jMenuItem2.setBackground(new java.awt.Color(48, 55, 79));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_sign_out_20px.png"))); // NOI18N
        jMenuItem2.setText("Đăng xuất");
        jMenuItem2.setContentAreaFilled(false);
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuUser.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        TitleBar.setBackground(new java.awt.Color(197, 197, 197));
        TitleBar.setPreferredSize(new java.awt.Dimension(1500, 30));
        TitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleBarMouseDragged(evt);
            }
        });
        TitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TitleBarMouseClicked(evt);
            }
        });
        TitleBar.setLayout(new java.awt.BorderLayout());

        Name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Phần mềm Quản Lý Khách Sạn");
        Name.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                NameMouseDragged(evt);
            }
        });
        Name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NameMousePressed(evt);
            }
        });
        TitleBar.add(Name, java.awt.BorderLayout.CENTER);

        Actions.setBackground(new java.awt.Color(197, 197, 197));
        Actions.setPreferredSize(new java.awt.Dimension(100, 30));
        Actions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close.png"))); // NOI18N
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        Actions.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 3, -1, -1));

        maximize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/maximize1.png"))); // NOI18N
        maximize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maximize.setPreferredSize(new java.awt.Dimension(26, 26));
        maximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maximizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maximizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maximizeMouseExited(evt);
            }
        });
        Actions.add(maximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 3, 30, -1));

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/minimizes.png"))); // NOI18N
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        Actions.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, -1, -1));

        TitleBar.add(Actions, java.awt.BorderLayout.EAST);

        lblIconApp.setBackground(new java.awt.Color(153, 255, 102));
        lblIconApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/iconApp.png"))); // NOI18N
        lblIconApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TitleBar.add(lblIconApp, java.awt.BorderLayout.LINE_START);

        getContentPane().add(TitleBar, java.awt.BorderLayout.PAGE_START);

        Menus.setBackground(new java.awt.Color(204, 204, 204));
        Menus.setPreferredSize(new java.awt.Dimension(250, 708));
        Menus.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(48, 55, 79));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 27)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        Menus.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        Menu.setBackground(new java.awt.Color(204, 204, 204));
        Menu.setLayout(new javax.swing.BoxLayout(Menu, javax.swing.BoxLayout.Y_AXIS));
        Menus.add(Menu, java.awt.BorderLayout.CENTER);

        getContentPane().add(Menus, java.awt.BorderLayout.WEST);

        Dashboard.setLayout(new java.awt.BorderLayout());

        Top.setBackground(new java.awt.Color(48, 55, 79));
        Top.setPreferredSize(new java.awt.Dimension(1250, 60));
        Top.setLayout(new java.awt.GridLayout(1, 3));

        jPanel6.setBackground(new java.awt.Color(48, 55, 79));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Top.add(jPanel6);

        jPanel8.setBackground(new java.awt.Color(48, 55, 79));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        Top.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(48, 55, 79));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jPanel10.setBackground(new java.awt.Color(48, 55, 79));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel10);

        jPanel11.setBackground(new java.awt.Color(48, 55, 79));
        jPanel11.setLayout(new java.awt.BorderLayout());

        lblLogout.setBackground(new java.awt.Color(48, 55, 79));
        lblLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/logout1.png"))); // NOI18N
        lblLogout.setText("          ");
        lblLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogoutMouseExited(evt);
            }
        });
        jPanel11.add(lblLogout, java.awt.BorderLayout.EAST);

        btnUser.setBackground(new java.awt.Color(48, 55, 79));
        btnUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUser.setForeground(new java.awt.Color(255, 255, 255));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/user-1.png"))); // NOI18N
        btnUser.setText("Admin");
        btnUser.setBorder(null);
        btnUser.setContentAreaFilled(false);
        btnUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUser.setIconTextGap(10);
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUserMouseExited(evt);
            }
        });
        jPanel11.add(btnUser, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel11);

        Top.add(jPanel9);

        Dashboard.add(Top, java.awt.BorderLayout.PAGE_START);

        Contents.setBackground(new java.awt.Color(255, 255, 255));

        Content.setBackground(new java.awt.Color(255, 255, 255));
        Content.setLayout(new java.awt.BorderLayout());

        lblBG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBG.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Content.add(lblBG, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout ContentsLayout = new javax.swing.GroupLayout(Contents);
        Contents.setLayout(ContentsLayout);
        ContentsLayout.setHorizontalGroup(
            ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentsLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        ContentsLayout.setVerticalGroup(
            ContentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Dashboard.add(Contents, java.awt.BorderLayout.CENTER);

        getContentPane().add(Dashboard, java.awt.BorderLayout.CENTER);

        Bottom.setBackground(new java.awt.Color(48, 55, 79));
        Bottom.setPreferredSize(new java.awt.Dimension(1500, 25));
        Bottom.setLayout(new java.awt.GridLayout(1, 5));

        jPanel2.setBackground(new java.awt.Color(48, 55, 79));

        lblGioiThieu.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        lblGioiThieu.setForeground(new java.awt.Color(255, 255, 255));
        lblGioiThieu.setText("Hệ thống quản lý Khách Sạn PhucCo.Ltd®");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblGioiThieu, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGioiThieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        Bottom.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(48, 55, 79));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        Bottom.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(48, 55, 79));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        Bottom.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(48, 55, 79));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_alarm_clock_20px.png"))); // NOI18N

        lblDongHo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 255, 255));
        lblDongHo.setText("HELLO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
            .addComponent(lblDongHo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Bottom.add(jPanel5);

        jPanel7.setBackground(new java.awt.Color(48, 55, 79));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_planner_20px.png"))); // NOI18N

        lblNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNgay.setForeground(new java.awt.Color(255, 255, 255));
        lblNgay.setText("HELLO");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        Bottom.add(jPanel7);

        getContentPane().add(Bottom, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(1500, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameMousePressed
        xx = evt.getX();
        yy = evt.getY();


    }//GEN-LAST:event_NameMousePressed

    private void NameMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
//        this.setExtendedState(MainForm.NORMAL);
    }//GEN-LAST:event_NameMouseDragged

    //EventForm
    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(MainForm.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_minimizeMouseExited

    private void maximizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseClicked
        if (this.getWidth() == 1500) {
            this.setExtendedState(MainForm.MAXIMIZED_BOTH);
        } else {
            this.setExtendedState(MainForm.NORMAL);
        }
    }//GEN-LAST:event_maximizeMouseClicked

    private void maximizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_maximizeMouseEntered

    private void maximizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maximizeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_maximizeMouseExited

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        if (DialogHelper.confirm(Content, "Bạn có thật sự muốn thoát?")) {
            System.exit(0);
        }
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMouseExited

    private void btnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseEntered
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/user-2.png")));
        btnUser.setForeground(new Color(255, 101, 101));
    }//GEN-LAST:event_btnUserMouseEntered

    private void btnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseExited
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/user-1.png")));
        btnUser.setForeground(Color.white);
    }//GEN-LAST:event_btnUserMouseExited

    private void lblLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseClicked
        this.logoff();
    }//GEN-LAST:event_lblLogoutMouseClicked

    private void lblLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseEntered
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/logout2.png")));
    }//GEN-LAST:event_lblLogoutMouseEntered

    private void lblLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogoutMouseExited
        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/logout1.png")));
    }//GEN-LAST:event_lblLogoutMouseExited

    private void TitleBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseClicked
        if (evt.getClickCount() == 2) {
            if (this.getWidth() == 1500) {
                this.setExtendedState(MainForm.MAXIMIZED_BOTH);
            } else {
                this.setExtendedState(MainForm.NORMAL);
            }
        }
    }//GEN-LAST:event_TitleBarMouseClicked

    private void NameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NameMouseClicked
        if (evt.getClickCount() == 2) {
            if (this.getWidth() == 1500) {
                this.setExtendedState(MainForm.MAXIMIZED_BOTH);
            } else {
                this.setExtendedState(MainForm.NORMAL);
            }
        }
    }//GEN-LAST:event_NameMouseClicked

    private void TitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseDragged
        this.setExtendedState(MainForm.NORMAL);
    }//GEN-LAST:event_TitleBarMouseDragged

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        btnUser.setAlignmentX(RIGHT_ALIGNMENT);
        MenuUser.show(btnUser, btnUser.getX(), btnUser.getY() + 55);
    }//GEN-LAST:event_btnUserMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.openUserPanel();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.logoff();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Actions;
    private javax.swing.JPanel Bottom;
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Contents;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel Menu;
    private javax.swing.JPopupMenu MenuUser;
    private javax.swing.JPanel Menus;
    private javax.swing.JLabel Name;
    private javax.swing.JPanel TitleBar;
    private javax.swing.JPanel Top;
    private javax.swing.JToggleButton btnUser;
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblBG;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblGioiThieu;
    private javax.swing.JLabel lblIconApp;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblNgay;
    private javax.swing.JLabel maximize;
    private javax.swing.JLabel minimize;
    // End of variables declaration//GEN-END:variables

    //Initiailize
    void init() {
        this.setLocationRelativeTo(null);
        this.setIconImage((ShareHelper.APP_ICON));
        this.setTitle("PHẦN MỀM QUẢN LÝ KHÁCH SẠN PHUCCO.LTD");
        this.loadMenu();
        new Timer(1000, new ActionListener() {
            SimpleDateFormat time = new SimpleDateFormat("hh:mm:ss a");
            SimpleDateFormat date = new SimpleDateFormat("dd/MM/yyyy");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(time.format(new Date()));
                lblNgay.setText(date.format(new Date()));
            }
        }).start();
        this.openWelcome();
        this.openLogin();
        this.openLoader();
        this.toFront();
        if (!ShareHelper.authenticated()) {
            System.exit(0);
        }
        Content.add(new ManHinhChinh());
    }

    //LoadMenu
    private void loadMenu() {
        ImageIcon iconMHC = new ImageIcon(getClass().getResource("../Images/icons/home1.png"));
        ImageIcon iconSub = new ImageIcon(getClass().getResource("../Images/icons/sub.png"));
        ImageIcon iconList = new ImageIcon(getClass().getResource("../Images/icons/iconSub.png"));
        ImageIcon iconQLP = new ImageIcon(getClass().getResource("../Images/icons/QLP1.png"));
        ImageIcon iconQLKH = new ImageIcon(getClass().getResource("../Images/icons/QLKH1.png"));
        ImageIcon iconQLNV = new ImageIcon(getClass().getResource("../Images/icons/QLNV1.png"));
        ImageIcon iconQLDV = new ImageIcon(getClass().getResource("../Images/icons/QLDV1.png"));
        ImageIcon iconQLMKM = new ImageIcon(getClass().getResource("../Images/icons/QLMKM1.png"));
        ImageIcon iconQLDT = new ImageIcon(getClass().getResource("../Images/icons/QLDT1.png"));
        ImageIcon iconBC = new ImageIcon(getClass().getResource("../Images/icons/BC1.png"));
        ImageIcon iconGT = new ImageIcon(getClass().getResource("../Images/icons/GT1.png"));

        //Submenu
        MenuItems subQLP1 = new MenuItems(iconList, "Sơ Đồ Phòng", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Content.removeAll();
                Content.add(new SoDoPhong());
                new Loading_Frame(new javax.swing.JFrame(), true).setVisible(true);
                Content.repaint();
                Content.revalidate();

            }
        });
        MenuItems subQLP2 = new MenuItems(iconList, "Loại Phòng", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Content.removeAll();
                Content.add(new LoaiPhong());
                Content.repaint();
                Content.revalidate();
            }
        });
        MenuItems subQLKH3 = new MenuItems(iconList, "Hóa Đơn", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Content.removeAll();
                Content.add(new HoaDon());
                Content.repaint();
                Content.revalidate();
            }
        });
        MenuItems subQLKH1 = new MenuItems(iconList, "Thông Tin KH", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Content.removeAll();
                Content.add(new KhachHang());
                Content.repaint();
                Content.revalidate();
            }
        });
        MenuItems subQLKH2 = new MenuItems(iconList, "Phiếu Đăng Kí", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Content.removeAll();
                Content.add(new PhieuDangKy());
                Content.repaint();
                Content.revalidate();
            }
        });

        //Menu
        MenuItems menuMHC = new MenuItems(iconMHC, "Màn Hình Chính", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Content.removeAll();
                Content.add(new ManHinhChinh());
                Content.repaint();
                Content.revalidate();
//                bgImage();
            }
        });
        MenuItems menuQLP = new MenuItems(iconQLP, iconSub, "Quản Lý Phòng", null, subQLP1, subQLP2);
        MenuItems menuQLKH = new MenuItems(iconQLKH, iconSub, "Khách Hàng", null, subQLKH1, subQLKH2, subQLKH3);
        MenuItems menuQLNV = new MenuItems(iconQLNV, "Nhân Viên", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (ShareHelper.role == 2) {
                    Content.removeAll();
                    Content.add(new NhanVien());
                    Content.repaint();
                    Content.revalidate();
                } else {
                    DialogHelper.alert(Content, "Chức năng không dành cho nhân viên");
                }
            }
        });
        MenuItems menuQLDV = new MenuItems(iconQLDV, "Quản Lý Dịch Vụ", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Content.removeAll();
                Content.add(new DichVu());
                Content.repaint();
                Content.revalidate();
            }
        });
        MenuItems menuQLMKM = new MenuItems(iconQLMKM, "Mã Khuyến Mãi", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Content.removeAll();
                Content.add(new MaKhuyenMai());
                Content.repaint();
                Content.revalidate();
            }
        });
        MenuItems subBC1 = new MenuItems(iconList, "Doanh Thu", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (ShareHelper.role == 2) {
                    Content.removeAll();
                    Content.add(new aBieuDo());
                    Content.repaint();
                    Content.revalidate();
                } else {
                    DialogHelper.alert(Content, "Chức năng không dành cho nhân viên");
                }
            }
        });
        MenuItems subBC2 = new MenuItems(iconList, "Khách Hàng", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (ShareHelper.role == 2) {
                    Content.removeAll();
                    Content.add(new BieuDo2());
                    Content.repaint();
                    Content.revalidate();
                } else {
                    DialogHelper.alert(Content, "Chức năng không dành cho nhân viên");
                }
            }
        });
        MenuItems menuBC = new MenuItems(iconBC, iconSub, "Báo Cáo", null, subBC1, subBC2);
        MenuItems menuGT;
        menuGT = new MenuItems(iconGT, "Giới Thiệu", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                new GioiThieu(null, true).setVisible(true);
            }
        });

        addMenu(menuMHC, menuQLP, menuQLKH, menuQLNV, menuQLDV, menuQLMKM, menuBC, menuGT);
    }

    private void addMenu(MenuItems... menu) {
        for (int i = 0; i < menu.length; i++) {
            Menu.add(menu[i]);
            ArrayList<MenuItems> subMenu = menu[i].getSubMenu();
            for (MenuItems m : subMenu) {
                addMenu(m);
            }
        }
        Menu.revalidate();
    }

    void openLogin() {
        new SignIn_Form(this, true).setVisible(true);
        try {
            btnUser.setText(ShareHelper.user.getMaNV());
        } catch (Exception e) {
        }
    }

    void openWelcome() {
        new SplashForm(this, true).setVisible(true);
    }

    void openLoader() {
        new Loading_Frame(this, true).setVisible(true);
    }

    void openUserPanel() {
        ThongTinTaiKhoan jd = new ThongTinTaiKhoan(new javax.swing.JFrame(), true);
        jd.setVisible(true);
        jd.setModal(true);
        jd.setAlwaysOnTop(true);
        jd.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
    }

    void logoff() {
        ShareHelper.logoff();
        this.dispose();
        new MainForm().setVisible(true);
    }
}
