/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI;

import java.awt.Dialog;

/**
 *
 * @author Dell Vostro
 */
public class PopupXacNhan extends javax.swing.JDialog {
    int trangthai;
    String maPhong;
    String tenphong;
    static int xx, yy;
    /**
     * Creates new form ChuyenTrangThai
     */
    public PopupXacNhan(java.awt.Frame parent, boolean modal, String masoPhong, String tenPhong, int trangThai) {
        super(parent, modal);
        initComponents();
        trangthai=trangThai;
        maPhong=masoPhong;
        tenphong=tenPhong;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClose3 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnUpdate1 = new javax.swing.JButton();
        chkNhanPhong = new javax.swing.JCheckBox();
        chkDat = new javax.swing.JCheckBox();

        lblClose3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close.png"))); // NOI18N
        lblClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClose3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClose3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblClose3MousePressed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 55, 79)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel.setText("Chức năng bạn muốn sử dụng?");
        jPanel3.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("Tiếp tục");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, -1));

        btnUpdate1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate1.setText("Thoát");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, -1));

        chkNhanPhong.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(chkNhanPhong);
        chkNhanPhong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkNhanPhong.setText("Nhận/Lấy phòng");
        jPanel3.add(chkNhanPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        chkDat.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(chkDat);
        chkDat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chkDat.setText("Đặt phòng");
        jPanel3.add(chkDat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseClicked

    }//GEN-LAST:event_lblClose3MouseClicked

    private void lblClose3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseEntered

    }//GEN-LAST:event_lblClose3MouseEntered

    private void lblClose3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseExited

    }//GEN-LAST:event_lblClose3MouseExited

    private void lblClose3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MousePressed

    }//GEN-LAST:event_lblClose3MousePressed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        this.next();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdate1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnUpdate1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupXacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupXacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupXacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupXacNhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                PopupXacNhan dialog = new PopupXacNhan(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkDat;
    private javax.swing.JCheckBox chkNhanPhong;
    private javax.swing.JLabel jLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblClose3;
    // End of variables declaration//GEN-END:variables
    void next(){
        if(chkDat.isSelected()&&trangthai==0){
        WizardProgress jd = new WizardProgress(new javax.swing.JFrame(), true,maPhong,tenphong,0);
        jd.setVisible(true);
        jd.setModal(true);
        jd.setAlwaysOnTop(true);
        jd.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        this.dispose();
        } else if(chkNhanPhong.isSelected()&&trangthai==0){
         WizardProgress jd = new WizardProgress(new javax.swing.JFrame(), true,maPhong,tenphong,2);
        jd.setVisible(true);
        jd.setModal(true);
        jd.setAlwaysOnTop(true);
        jd.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
        this.dispose();
        } 
    }
}
