/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI;

import com.team3.DAO.DAO_NhanVien;
import com.team3.Helpers.DialogHelper;
import com.team3.Helpers.ShareHelper;
import java.awt.Dialog;

/**
 *
 * @author Dell Vostro
 */
public class ResetPass_Form extends javax.swing.JFrame {

    static int xx, yy;
    
    DAO_NhanVien dao = new DAO_NhanVien();
    /**
     * Creates new form ResetPass_Form
     */
    public ResetPass_Form(java.awt.Frame parent, boolean modal) {
        initComponents();
        this.setLocationRelativeTo(null);
        btnViewPass1.setVisible(false);
    }

    void resetPass(){
        try {
            String pass = new String(txtPassword.getPassword());
            String confirm = new String(txtRePassword.getPassword());
            if (pass.length() > 0) {
                if (confirm.trim().equalsIgnoreCase(pass.trim())) {
                    dao.updateFGPass(pass.trim(), ShareHelper.email);
                    DialogHelper.alert(this, "Đổi mật khẩu thành công");
                    ShareHelper.email = null;
                    ShareHelper.verify = null;
                    ShareHelper.user = null;
                    this.openSignIn();  
                    this.dispose();
                }else{
                    DialogHelper.alert(this, "Xác nhận mật khẩu không đúng!");
                    txtRePassword.requestFocus();
                }
            }else{
                DialogHelper.alert(this, "Mật khẩu không được để trống!");
                txtPassword.requestFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    void openSignIn() {
        this.setVisible(false);
        SignIn_Form jd = new SignIn_Form(new javax.swing.JFrame(), true);
        jd.setVisible(true);
        jd.setModal(true);
        jd.setAlwaysOnTop(true);
        jd.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        btnAccept = new javax.swing.JButton();
        lblMinimize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        btnViewPass1 = new javax.swing.JToggleButton();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 118, 230, -1));

        txtRePassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtRePassword.setBorder(null);
        jPanel1.add(txtRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 230, -1));

        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/accept2.png"))); // NOI18N
        btnAccept.setBorder(null);
        btnAccept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAccept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAcceptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAcceptMouseExited(evt);
            }
        });
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccept, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, -1, -1));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/minimize1.png"))); // NOI18N
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 5, -1, -1));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close1.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 5, -1, -1));

        btnViewPass1.setBackground(new java.awt.Color(204, 204, 204));
        btnViewPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/eyes.png"))); // NOI18N
        btnViewPass1.setBorder(null);
        btnViewPass1.setContentAreaFilled(false);
        btnViewPass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewPass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPass1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 40, 20));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/Reset.png"))); // NOI18N
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_bgMouseDragged

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/minimize2.png")));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/minimize1.png")));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        setState(this.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close2.png")));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close1.png")));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_lblCloseMousePressed

    private void btnAcceptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptMouseEntered
        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/accept1.png")));
    }//GEN-LAST:event_btnAcceptMouseEntered

    private void btnAcceptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceptMouseExited
        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/accept2.png")));
    }//GEN-LAST:event_btnAcceptMouseExited

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        this.resetPass();
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtRePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRePasswordMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtRePasswordMouseClicked

    private void btnViewPass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPass1ActionPerformed
        if (btnViewPass1.isSelected()) {
            btnViewPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/hideeyes.png")));
            txtPassword.setEchoChar((char) 0);
            txtRePassword.setEchoChar((char) 0);
        } else {
            btnViewPass1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/eyes.png")));
            txtPassword.setEchoChar('•');
            txtRePassword.setEchoChar('•');
        }
    }//GEN-LAST:event_btnViewPass1ActionPerformed

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        String pass = new String(txtPassword.getPassword());
        if (pass.length() > 0) {
            btnViewPass1.setVisible(true);
            btnViewPass1.setEnabled(true);
        } else if (pass.length() == 0) {
            btnViewPass1.setVisible(false);
            btnViewPass1.setEnabled(false);
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResetPass_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResetPass_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResetPass_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResetPass_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ResetPass_Form dialog = new ResetPass_Form(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnAccept;
    private javax.swing.JToggleButton btnViewPass1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    // End of variables declaration//GEN-END:variables
}
