/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI;

import com.team3.DAO.DAO_NhanVien;
import com.team3.Helpers.DialogHelper;
import com.team3.Model.Model_NhanVien;
import static com.team3.UI.SignUp_Form.xx;
import static com.team3.UI.SignUp_Form.yy;
import java.awt.Dialog;

/**
 *
 * @author Dell Vostro
 */
public class SignUp_Form extends javax.swing.JDialog {

    static int xx, yy;

    DAO_NhanVien nvd = new DAO_NhanVien();

    /**
     * Creates new form SignUp1_Form
     */
    public SignUp_Form() {
        initComponents();
        this.setLocationRelativeTo(null);
        btnViewPass.setVisible(false);
    }

    void register() {
        try {
            String pass = new String(txtPassword.getPassword());
            String confirm = new String(txtRePassword.getPassword());
            Model_NhanVien model = getModel();
            Model_NhanVien model2 = nvd.findByEmail(txtEmail.getText());
            Model_NhanVien model3 = nvd.findById(txtUserName.getText());
            String ho = txtHo.getText();
            String ten = txtTen.getText();
            String email = txtEmail.getText();
            String regex = "^[\\w-_\\.[^0-9]]+\\@[\\w&&[a-z][^0-9]]+\\.[\\w&&[a-z][^0-9]]+[\\.[a-z]]+$";
            if(txtUserName.getText().length()==0){
                DialogHelper.alert(this, "Không được bỏ trống Tên đăng nhập");
                txtUserName.requestFocus();
            }else if(model3 != null){
                DialogHelper.alert(this, "Tài khoản đã tồn tại");
                txtUserName.requestFocus();
            } else if(pass.length()<5){
                DialogHelper.alert(this, "Mật khẩu phải lớn hơn 5 kí tự");
                txtPassword.requestFocus();
            } else if(!confirm.equals(pass)){
                DialogHelper.alert(this, "Xác nhận mật khẩu không đúng!");
                txtRePassword.requestFocus();
            } else if(ho.chars().allMatch(Character::isDigit)==true 
                    &&ho.length()==0
                    ||ten.chars().allMatch(Character::isDigit)==true
                    &&ten.length()==0
            ){
                DialogHelper.alert(this, "Họ Tên phải là chữ cái và không được bỏ trống!");
                txtHo.requestFocus();
            } else if(!email.matches(regex)||email.length()==0){
                DialogHelper.alert(this, "Email không đúng dạng!");
                txtEmail.requestFocus();
            } else if(model2!=null){
                DialogHelper.alert(this, "Email đã có người đăng kí!");
                txtEmail.requestFocus();                     
            } else if (!chkConfirm.isSelected()){
                    DialogHelper.alert(this, "Bạn chưa đồng ý với điều khoản");
            } else{
                nvd.insert(model);
                DialogHelper.alert(this, "Đăng kí thành công!!");
                this.openSignIn();
                
            }                 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    void openSignIn() {
        this.setVisible(false);
        SignIn_Form jd = new SignIn_Form(new javax.swing.JFrame(), true);
        jd.setVisible(true);
        jd.setModal(true);
        jd.setAlwaysOnTop(true);
        jd.setModalityType(Dialog.ModalityType.APPLICATION_MODAL);
    }
    void exit() {
        if (DialogHelper.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?")) {
            System.exit(0);
        }
    }
    Model_NhanVien getModel() {
        try {
            String pass = new String(txtPassword.getPassword());
            Model_NhanVien model = new Model_NhanVien();
            model.setMaNV(txtUserName.getText());
            model.setMatKhau(pass);
            model.setHo(txtHo.getText());
            model.setTen(txtTen.getText());
            model.setEmail(txtEmail.getText());
            model.setDiaChi("0");
            model.setSDT("0");
            model.setGioiTinh(true);
            model.setHinh("0");
            model.setVaiTro(0);
            return model;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIconApp = new javax.swing.JLabel();
        btnViewPass = new javax.swing.JToggleButton();
        txtPassword = new javax.swing.JPasswordField();
        txtRePassword = new javax.swing.JPasswordField();
        txtUserName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTen = new javax.swing.JTextField();
        txtHo = new javax.swing.JTextField();
        chkConfirm = new javax.swing.JCheckBox();
        btnBack = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        lblClose = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIconApp.setBackground(new java.awt.Color(153, 255, 102));
        lblIconApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/iconApp.png"))); // NOI18N
        lblIconApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblIconApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        btnViewPass.setBackground(new java.awt.Color(204, 204, 204));
        btnViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/eyes.png"))); // NOI18N
        btnViewPass.setBorder(null);
        btnViewPass.setBorderPainted(false);
        btnViewPass.setContentAreaFilled(false);
        btnViewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPassActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 40, 30));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 333, 260, -1));

        txtRePassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtRePassword.setBorder(null);
        jPanel1.add(txtRePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 403, 300, -1));

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtUserName.setBorder(null);
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 262, 300, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtEmail.setBorder(null);
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 191, 300, -1));

        txtTen.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTen.setBorder(null);
        jPanel1.add(txtTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, -1));

        txtHo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtHo.setBorder(null);
        jPanel1.add(txtHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 120, 140, -1));

        chkConfirm.setBackground(new java.awt.Color(255, 255, 255));
        chkConfirm.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        chkConfirm.setText("Tôi đồng ý với Điều Khoản và Chính Sách Bảo Mật");
        jPanel1.add(chkConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 300, -1));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/back1.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBackMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBackMouseExited(evt);
            }
        });
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/register2.png"))); // NOI18N
        btnRegister.setBorder(null);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegisterMouseExited(evt);
            }
        });
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close1.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 5, -1, -1));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/minimize1.png"))); // NOI18N
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 5, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/SignUp.png"))); // NOI18N
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseEntered
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/register1.png")));
    }//GEN-LAST:event_btnRegisterMouseEntered

    private void btnRegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegisterMouseExited
        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/register2.png")));
    }//GEN-LAST:event_btnRegisterMouseExited

    private void btnBackMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseEntered
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/back2.png")));
    }//GEN-LAST:event_btnBackMouseEntered

    private void btnBackMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseExited
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/back1.png")));
    }//GEN-LAST:event_btnBackMouseExited

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/minimize2.png")));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/minimize1.png")));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
//        setState(this.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close2.png")));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close1.png")));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_lblCloseMousePressed

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_bgMouseDragged

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        this.register();
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtHoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoActionPerformed
        // TODO add your handling code here:
        txtHo.setText("");
    }//GEN-LAST:event_txtHoActionPerformed

    private void txtTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenActionPerformed
        // TODO add your handling code here:
        txtTen.setText("");
    }//GEN-LAST:event_txtTenActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
        txtUserName.setText("");
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtRePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRePasswordActionPerformed
        // TODO add your handling code here:
        txtRePassword.setText("");
    }//GEN-LAST:event_txtRePasswordActionPerformed

    private void txtHoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHoMouseClicked
        // TODO add your handling code here:
        txtHo.setText("");
    }//GEN-LAST:event_txtHoMouseClicked

    private void txtTenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTenMouseClicked
        // TODO add your handling code here:
        txtTen.setText("");
    }//GEN-LAST:event_txtTenMouseClicked

    private void txtEmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmailMouseClicked
        // TODO add your handling code here:
        txtEmail.setText("");
    }//GEN-LAST:event_txtEmailMouseClicked

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked
        // TODO add your handling code here:
        txtUserName.setText("");
    }//GEN-LAST:event_txtUserNameMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtRePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtRePasswordMouseClicked
        // TODO add your handling code here:
        txtRePassword.setText("");
    }//GEN-LAST:event_txtRePasswordMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.openSignIn();
    
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPassActionPerformed
       if (btnViewPass.isSelected()) {
            btnViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/hideeyes.png")));
            txtPassword.setEchoChar((char) 0);
            txtRePassword.setEchoChar((char) 0);
        } else {
            btnViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/eyes.png")));
            txtPassword.setEchoChar('•');
            txtRePassword.setEchoChar('•');
        }
    }//GEN-LAST:event_btnViewPassActionPerformed

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        String pass = new String(txtPassword.getPassword());
        if (pass.length() > 0) {
            btnViewPass.setVisible(true);
            btnViewPass.setEnabled(true);
        } else if (pass.length() == 0) {
            btnViewPass.setVisible(false);
            btnViewPass.setEnabled(false);
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JToggleButton btnViewPass;
    private javax.swing.JCheckBox chkConfirm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblIconApp;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHo;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtRePassword;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
