/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI;

import com.team3.DAO.DAO_NhanVien;
import com.team3.Helpers.DialogHelper;
import com.team3.Helpers.ShareHelper;
import com.team3.Model.Model_NhanVien;
import java.awt.Color;
import java.awt.event.KeyEvent;


/**
 *
 * @author Dell Vostro
 */
public class SignIn_Form extends javax.swing.JDialog {

    static int xx, yy;

    /**
     * Creates new form Login_Form
     */
    public SignIn_Form(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    DAO_NhanVien dao = new DAO_NhanVien();

    void init() {
        btnViewPass.setVisible(false);
        btnViewPass.setEnabled(false);
        setLocationRelativeTo(null);
        this.setIconImage((ShareHelper.APP_ICON));
    }

    void login() {
        String manv = txtUserName.getText();
        String matKhau = new String(txtPassword.getPassword());
        try {
            Model_NhanVien nhanVien = dao.findById(manv);
            if (nhanVien != null) {
                String matKhau2 = nhanVien.getMatKhau();

                if (matKhau.equals(matKhau2)) {
                    int role = nhanVien.getVaiTro();
                    ShareHelper.user = nhanVien;
                    ShareHelper.role = role;
                    DialogHelper.alert(this, "Đăng nhập thành công!");
                    this.dispose();
                } else {
                    DialogHelper.alert(this, "Sai tên đăng nhập hoặc mật khẩu!");
                }
            } else {
                DialogHelper.alert(this, "Sai tên đăng nhập hoặc mật khẩu!");
            }
        } catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void exit() {
        if (DialogHelper.confirm(this, "Bạn có muốn thoát khỏi ứng dụng không?")) {
            System.exit(0);
        }
    }

    void openForgot() {
        this.setVisible(false);
        ForgetPass_Form jd = new ForgetPass_Form(new javax.swing.JFrame(), true);
        jd.setVisible(true);

    }
    void openSignup() {
        this.setVisible(false);
        SignUp_Form jd = new SignUp_Form();
        jd.setVisible(true);
    }
    
    void openQRScan() {
        this.setVisible(false);
        QRScanner jd = new QRScanner(new javax.swing.JFrame(), true);
        jd.setModal(true);
        jd.setVisible(true);
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblGetQR = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblText = new javax.swing.JLabel();
        lblSignUp = new javax.swing.JLabel();
        lblForgetPWD = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblMinimize = new javax.swing.JLabel();
        btnViewPass = new javax.swing.JToggleButton();
        lblClose = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGetQR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblGetQR.setForeground(new java.awt.Color(0, 0, 0));
        lblGetQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/qrico.png"))); // NOI18N
        lblGetQR.setText("Login by QRCode®");
        lblGetQR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGetQRMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGetQRMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGetQRMouseExited(evt);
            }
        });
        jPanel1.add(lblGetQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, 30));

        txtUserName.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtUserName.setText("ducnm");
        txtUserName.setBorder(null);
        txtUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUserNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 270, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtPassword.setText("123456");
        txtPassword.setBorder(null);
        txtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPasswordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPasswordKeyTyped(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 230, -1));

        lblText.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblText.setForeground(new java.awt.Color(113, 113, 113));
        lblText.setText("Bạn chưa có tài khoản?");
        lblText.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(lblText, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 320, -1, 20));

        lblSignUp.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblSignUp.setForeground(new java.awt.Color(48, 55, 79));
        lblSignUp.setText("Đăng Ký");
        lblSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSignUpMouseExited(evt);
            }
        });
        jPanel1.add(lblSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        lblForgetPWD.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblForgetPWD.setForeground(new java.awt.Color(113, 113, 113));
        lblForgetPWD.setText("Quên mật khẩu?");
        lblForgetPWD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblForgetPWD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblForgetPWDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblForgetPWDMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblForgetPWDMouseExited(evt);
            }
        });
        jPanel1.add(lblForgetPWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 215, -1, -1));

        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/exit1.png"))); // NOI18N
        btnCancel.setBorder(null);
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/login2.png"))); // NOI18N
        btnLogin.setBorder(null);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, -1, -1));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/minimize1.png"))); // NOI18N
        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 5, -1, -1));

        btnViewPass.setBackground(new java.awt.Color(204, 204, 204));
        btnViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/eyes.png"))); // NOI18N
        btnViewPass.setBorder(null);
        btnViewPass.setBorderPainted(false);
        btnViewPass.setContentAreaFilled(false);
        btnViewPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPassActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 40, 20));

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close1.png"))); // NOI18N
        lblClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 5, -1, -1));

        bg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/Signin.png"))); // NOI18N
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed

    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed

    }//GEN-LAST:event_lblMinimizeMousePressed

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/minimize2.png")));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/minimize1.png")));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close2.png")));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close1.png")));
    }//GEN-LAST:event_lblCloseMouseExited

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/exit2.png")));
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/exit1.png")));
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/login1.png")));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/UI/login2.png")));
    }//GEN-LAST:event_btnLoginMouseExited

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void btnViewPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPassActionPerformed
        if (btnViewPass.isSelected()) {
            btnViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/hideeyes.png")));
            txtPassword.setEchoChar((char) 0);
        } else {
            btnViewPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/eyes.png")));
            txtPassword.setEchoChar('•');
        }
    }//GEN-LAST:event_btnViewPassActionPerformed

    private void txtPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyTyped
        String pass = new String(txtPassword.getPassword());
        if (pass.length() > 0) {
            btnViewPass.setVisible(true);
            btnViewPass.setEnabled(true);
        } else if (pass.length() == 0) {
            btnViewPass.setVisible(false);
            btnViewPass.setEnabled(false);
        }
    }//GEN-LAST:event_txtPasswordKeyTyped

    private void txtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPasswordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.login();
        }
        if (evt.getKeyCode() == KeyEvent.VK_UP) {
            txtUserName.requestFocus();
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            btnLogin.requestFocus();
        }
    }//GEN-LAST:event_txtPasswordKeyPressed

    private void txtUserNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.login();
        }
        if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            txtPassword.requestFocus();
        }
    }//GEN-LAST:event_txtUserNameKeyPressed

    private void lblSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseEntered
        lblSignUp.setForeground(Color.decode("#FF374F"));
    }//GEN-LAST:event_lblSignUpMouseEntered

    private void lblSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseExited
        lblSignUp.setForeground(Color.decode("#30374F"));
    }//GEN-LAST:event_lblSignUpMouseExited

    private void lblForgetPWDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgetPWDMouseEntered
        lblForgetPWD.setForeground(Color.decode("#FF374F"));
    }//GEN-LAST:event_lblForgetPWDMouseEntered

    private void lblForgetPWDMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgetPWDMouseExited
        lblForgetPWD.setForeground(Color.decode("#717171"));
    }//GEN-LAST:event_lblForgetPWDMouseExited

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.exit();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        this.login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignUpMouseClicked
        this.openSignup();
    }//GEN-LAST:event_lblSignUpMouseClicked

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        this.exit();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblForgetPWDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblForgetPWDMouseClicked
        // TODO add your handling code here:           
        this.openForgot();

    }//GEN-LAST:event_lblForgetPWDMouseClicked

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked
        // TODO add your handling code here:
        txtUserName.setText("");
    }//GEN-LAST:event_txtUserNameMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        // TODO add your handling code here:
        txtPassword.setText("");
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void lblGetQRMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGetQRMouseClicked
            this.openQRScan();
    }//GEN-LAST:event_lblGetQRMouseClicked

    private void lblGetQRMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGetQRMouseEntered
        lblGetQR.setForeground(Color.red);
    }//GEN-LAST:event_lblGetQRMouseEntered

    private void lblGetQRMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGetQRMouseExited
        lblGetQR.setForeground(Color.BLACK);
    }//GEN-LAST:event_lblGetQRMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignIn_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignIn_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignIn_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignIn_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {               
                SignIn_Form dialog = new SignIn_Form(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton btnCancel;
    public static javax.swing.JButton btnLogin;
    private javax.swing.JToggleButton btnViewPass;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblForgetPWD;
    private javax.swing.JLabel lblGetQR;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblText;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
