/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.team3.UI;

import com.team3.DAO.DAO_DichVu;
import com.team3.DAO.DAO_HoaDon;
import com.team3.DAO.DAO_HoaDonChiTiet;
import com.team3.Helpers.DateHelper;
import com.team3.Helpers.DialogHelper;
import com.team3.Model.Model_DichVu;
import com.team3.Model.Model_HoaDon;
import com.team3.Model.Model_HoaDonChiTiet;
import com.team3.Model.Model_Phong;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Dell Vostro
 */
public class TheoDoiDichVu extends javax.swing.JDialog {
    DAO_DichVu dvDAO = new DAO_DichVu();
    DAO_HoaDonChiTiet hdctDAO = new DAO_HoaDonChiTiet();
    DAO_HoaDon hdDAO = new DAO_HoaDon();
    int maPhong;
    int maHD;
    int maPDK;
    static int xx, yy;
    /**
     * Creates new form ChuyenPhong
     */
    public TheoDoiDichVu(java.awt.Frame parent, boolean modal, int masoPhong, String ten,int masoPDK) {
        super(parent, modal);
        initComponents();
        maPhong=masoPhong;
        maPDK=masoPDK;
        Model_HoaDon mdl = this.hdDAO.findUnpaidByMaPDK(maPDK);
        if(mdl!=null){
        maHD=mdl.getMaHD();}
        lblPhong.setText(ten);
        this.loadAvailableServices();
        this.loaiUsingServices();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblClose3 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblIconApp = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblPhong = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lsDangCo = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDangDung = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSoluong = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(48, 55, 79));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblClose3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close.png"))); // NOI18N
        lblClose3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClose3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClose3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClose3MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblClose3MousePressed(evt);
            }
        });
        jPanel5.add(lblClose3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 0, 30, 30));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Bảng theo dõi dịch vụ");
        jPanel5.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 270, 30));

        lblIconApp.setBackground(new java.awt.Color(153, 255, 102));
        lblIconApp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconApp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/iconApp.png"))); // NOI18N
        lblIconApp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel5.add(lblIconApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 30, 30));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(48, 55, 79)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPhong.setText("P101");
        jPanel6.add(lblPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 80, 30));

        lsDangCo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lsDangCo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(lsDangCo);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 200, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Dịch vụ đang cung cấp");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 200, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Dịch vụ phòng đang sử dụng");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 230, 30));

        btnXoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_trash_18px.png"))); // NOI18N
        btnXoa.setText("<Hủy");
        btnXoa.setIconTextGap(10);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jPanel6.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 120, 30));

        tblDangDung.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblDangDung.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã dịch vụ", "Dịch vụ", "Số lượng", "Ngày thêm", "Ghi chú"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDangDung.setRowHeight(22);
        jScrollPane3.setViewportView(tblDangDung);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 680, 250));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Bảng cung cấp dịch vụ đang áp dụng trên phòng: ");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 330, 30));
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 1020, 10));

        txtGhiChu.setColumns(20);
        txtGhiChu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 810, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Số lượng");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Ghi chú (thêm)");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        txtSoluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSoluong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel6.add(txtSoluong, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 120, 30));

        btnThem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/icons8_add_shopping_cart_18px.png"))); // NOI18N
        btnThem.setText("Thêm>");
        btnThem.setIconTextGap(10);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel6.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 120, 30));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnUpdate.setText("Cập nhật số lượng DV");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel6.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 400, 180, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Bảng cung cấp dịch vụ đang áp dụng trên phòng: ");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 330, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1060, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblClose3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseClicked
        this.dispose();
    }//GEN-LAST:event_lblClose3MouseClicked

    private void lblClose3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseEntered
        lblClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close2.png")));
    }//GEN-LAST:event_lblClose3MouseEntered

    private void lblClose3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MouseExited
        lblClose3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/team3/Images/icons/close.png")));
    }//GEN-LAST:event_lblClose3MouseExited

    private void lblClose3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose3MousePressed
        this.dispose();
    }//GEN-LAST:event_lblClose3MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.addServicesToTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.removeRow();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        this.updateRow();
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TheoDoiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TheoDoiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TheoDoiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheoDoiDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                TheoDoiDichVu dialog = new TheoDoiDichVu(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblClose3;
    private javax.swing.JLabel lblIconApp;
    private javax.swing.JLabel lblPhong;
    public static javax.swing.JLabel lblTitle;
    private javax.swing.JList<String> lsDangCo;
    private javax.swing.JTable tblDangDung;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtSoluong;
    // End of variables declaration//GEN-END:variables
    void loadAvailableServices(){
        DefaultListModel model = new DefaultListModel();    
        model.removeAllElements();
        try {
            List<Model_DichVu> list = this.dvDAO.selectAvailableServices(maHD);
            if(list!=null){
            for (Model_DichVu dv : list) {
                model.addElement(dv.getMadv()+"--"+dv.getTen());
                lsDangCo.setModel(model);
                }  
            }
        }
        catch (Exception e) {
            DialogHelper.alert(this, "Lỗi truy vấn CSDL!");
            e.printStackTrace();
        }
    }
    void loaiUsingServices(){
        DefaultTableModel model = (DefaultTableModel) tblDangDung.getModel();
        model.setRowCount(0);
        try {
            List<Model_HoaDonChiTiet> list = this.hdctDAO.selectbyMaHoaDon(maHD);
            if(list!=null){
            for (Model_HoaDonChiTiet hdct : list) {
                Model_DichVu hd = this.dvDAO.findById(Integer.valueOf(hdct.getMaDV()));
                Object[] row = {
                  hdct.getMaHD(),
                  hdct.getMaDV(),
                  hd.getTen(),
                  hdct.getSoLuong(),
                  DateHelper.toString(hdct.getNgayThem(), new String[0]),
                  hdct.getGhiChu()
                };
                model.addRow(row);
                }
            } 
        } catch (Exception e) {
           DialogHelper.alert(this, "Lỗi truy vấn CSDL!");
            e.printStackTrace();
        }
    }
    void addServicesToTable(){
        int[] selectedIndex = lsDangCo.getSelectedIndices();
        int ok=0;
        if(selectedIndex.length ==0){DialogHelper.alert(this, "Bạn chưa chọn dịch vụ có sẵn!");}
        else if(txtSoluong.getText().length()==0){DialogHelper.alert(this, "Bạn chưa nhập số lượng");}
        else{    
            for(int i=0;i<selectedIndex.length;i++){            
                ListModel lModel = lsDangCo.getModel();
                DefaultTableModel tbModel = (DefaultTableModel)tblDangDung.getModel();
//                List ls = (List)lModel.getElementAt(selectedIndex[i]);
                String raw = lModel.getElementAt(selectedIndex[i]).toString().split("--")[0];
                Model_DichVu dv = this.dvDAO.findById(Integer.valueOf(raw));
                Object[] row = {
                  maHD,
                  dv.getMadv(),
                  dv.getTen(),
                  txtSoluong.getText(),
                  DateHelper.toString(DateHelper.now(), new String[0]),
                  txtGhiChu.getText()
                };
//                tbModel.addRow(row);
                Model_HoaDonChiTiet mdl = new Model_HoaDonChiTiet();
                mdl.setMaHD(maHD);
                mdl.setMaDV(dv.getMadv());
                mdl.setSoLuong(Integer.valueOf(txtSoluong.getText()));
                mdl.setNgayThem(DateHelper.toDate(DateHelper.toString(DateHelper.now(), new String[0]),new String[0]));
                mdl.setGhiChu(txtGhiChu.getText());
                if(Integer.valueOf(txtSoluong.getText())<=0){
                    DialogHelper.alert(this, "Số lượng không được nhỏ hơn 1!");
                    break;
                } else {
                    this.hdctDAO.insert(mdl);
                    ok=1;
                    }
                }
                btnThem.setEnabled(false);
                this.loadAvailableServices();
                this.loaiUsingServices();
                if(ok==1){
                DialogHelper.alert(this, "Đã thêm dịch vụ!");}
                btnThem.setEnabled(true);
            }
            
        }
    void updateRow(){
        int index=tblDangDung.getSelectedRow();
        int ok=0;
        if(index>=0){
            for(int i=0;i<this.tblDangDung.getRowCount();i++){
                Model_HoaDonChiTiet mdl = new Model_HoaDonChiTiet();
                mdl.setMaHD((Integer)this.tblDangDung.getValueAt(i, 0));
                mdl.setMaDV((Integer)this.tblDangDung.getValueAt(i, 1));
                
                mdl.setNgayThem(DateHelper.toDate((String)this.tblDangDung.getValueAt(i, 4),new String[0]));
                mdl.setGhiChu((String)this.tblDangDung.getValueAt(i, 5));
                if(this.tblDangDung.getValueAt(i, 3)==null||(Integer)this.tblDangDung.getValueAt(i, 3)<=0){
                    DialogHelper.alert(this, "Số lượng sai, vui lòng nhập đúng!");
                    break;
                } else{
                mdl.setSoLuong((Integer)this.tblDangDung.getValueAt(i, 3));
                
                this.hdctDAO.update(mdl);
                ok=1;
                }        
            }
            this.loadAvailableServices();
                this.loaiUsingServices();
                if(ok==1){
                DialogHelper.alert(this, "Đã Reload số lượng cho dịch vụ!");}
        } else{
           DialogHelper.alert(this, "Vui lòng chọn nội dung trong bảng để cập nhật"); 
        }
    }
    
    void removeRow(){
        int index=tblDangDung.getSelectedRow();
        if(index>=0){
            for(int i=0;i<this.tblDangDung.getSelectedRowCount();i++){
                int maHD = (Integer)this.tblDangDung.getValueAt(i, 0);
                int maDV = (Integer)this.tblDangDung.getValueAt(i, 1);
                this.hdctDAO.delete(maHD,maDV);
                
            }
            btnXoa.setEnabled(false);
                this.loadAvailableServices();
                this.loaiUsingServices();
                DialogHelper.alert(this, "Đã hủy dịch vụ!");
                btnXoa.setEnabled(true);
        } else{
           DialogHelper.alert(this, "Vui lòng chọn nội dung trong bảng để hủy"); 
        }
    }
}
